# The local Kummer image at $p = 2$ for $y^2 = x^3 - 1$

For $E : y^2 = x^3-1$ (curve `144a1`, $j = 0$, CM by $\mathbb{Z}[\zeta_3]$, the quadratic twist by
$-1$ of `36a1`) we write down an explicit finite set $V \subset E(\mathbb{Q}_2)$ representing
$E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$, and compute its image under the local Kummer map at $2$ as
explicit elements of
$$\mathbb{Q}_4 \;=\; \mathbb{Q}_2(\omega) \;=\; \mathbb{Q}_2(\sqrt{-3}) \;=\; \mathbb{Q}_2(\sqrt 5),$$
the unramified quadratic extension of $\mathbb{Q}_2$.

**The answer.** With $\omega = \zeta_3$ the map is $\delta(x,y) = x - \omega$, and
$$V = \{\mathcal{O},\ T,\ Q,\ Q+T\}
 = \Big\{\mathcal{O},\ (1,0),\ \big(\tfrac14, \tfrac38 y\big),\ (-3,\,-2y)\Big\},
 \qquad y = \sqrt{-7} \in \mathbb{Z}_2^\times,\ y \equiv 3 \ (8),$$
$$\operatorname{Im}(\delta) = \{1,\ 1-\omega,\ \omega-4,\ -3-\omega\}\cdot(\mathbb{Q}_4^\times)^2
 = \big\langle [1-\omega],\, [-3-\omega] \big\rangle \subset \mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2 .$$
The four classes are distinct for a one-line reason: their norms to $\mathbb{Q}_2$ are
$1,\ 3,\ 21/16,\ 7$, i.e. $1,3,5,7$ mod $8$ — *all four* square classes of $\mathbb{Z}_2^\times$ —
and a square has a square norm.

Compared with $y^2 = x^3+1$ the local picture at $2$ is **not** the same curve in disguise: there the
reduction is of type $\mathrm{IV}$ with $c_2 = 3$ and $E(\mathbb{Q}_2) \cong \mathbb{Z}_2\oplus\mathbb{Z}/6$;
here it is type $\mathrm{II}$ with $c_2 = 1$ and $E(\mathbb{Q}_2) \cong \mathbb{Z}_2\oplus\mathbb{Z}/2$, a
**pro-$2$ group**. One visible consequence: the coset of $Q$ contains no point with integral
$x$-coordinate at all — it is exactly $E_1 \smallsetminus E_2$, so $V$ *must* reach into the formal
group (§4).

Two engines are used below, deliberately: Sage's `Qq(4)` for honest $2$-adic arithmetic and
square testing, and the number field $\mathbb{Q}(\omega)$ with `hilbert_symbol` at its inert prime
above $2$ (whose completion *is* $\mathbb{Q}_4$) for the pairing computations of §7.  Everything
displayed symbolically is exact; only squareness is decided $2$-adically.

Companion to `local-kummer-p2.ipynb`, which does the same for $y^2 = x^3+1$; §8 compares the two.

## 1. The curve at $2$, and the size of $E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$

In [1]:
E = EllipticCurve([0,0,0,0,-1])             # y^2 = x^3 - 1
print("E             :", E)
print("discriminant  :", E.discriminant(), "=", factor(E.discriminant()))
print("j-invariant   :", E.j_invariant(), "   conductor:", E.conductor(),
      "   label:", E.cremona_label())
print("globally minimal:", E.is_minimal())
print("quadratic twist by -1:", E.quadratic_twist(-1).cremona_label())

ld = E.local_data(2)
print("at p = 2      : Kodaira", ld.kodaira_symbol(),
      "  f =", ld.conductor_valuation(), "  c_2 =", ld.tamagawa_number())
print("E(Q)          : torsion", E.torsion_subgroup().invariants(),
      "  rank", E.rank(), "  =>  E(Q) = { O, (1,0) }")

E             : Elliptic Curve defined by y^2 = x^3 - 1 over Rational Field
discriminant  : -432 = -1 * 2^4 * 3^3
j-invariant   : 0    conductor: 144    label: 144a1
globally minimal: True
quadratic twist by -1: 36a1
at p = 2      : Kodaira II   f = 4   c_2 = 1
E(Q)          : torsion (2,)   rank 0   =>  E(Q) = { O, (1,0) }


In [2]:
R.<X> = QQ[]
print("x^3 - 1 over Q :", factor(X^3 - 1))
print("-3 mod 8       :", Mod(-3, 8), "  so -3 is a square in Q_2 ?", Qp(2,20)(-3).is_square())
print("=> x^2 + x + 1 stays irreducible over Q_2, and E(Q_2)[2] = {O, (1,0)}, r_2 = 1")
print("=> #E(Q_2)/2E(Q_2) = #E(Q_2)[2] * |2|_2^(-1) = 2 * 2 = 4 = 2^(r_2+1)")
print()
print("psi_3          :", E.division_polynomial(3).factor())
print("   x = 0 needs y^2 = -1 :  i in Q_2 ?", Qp(2,20)(-1).is_square())
print("   x^3 = 4 needs 3 | v_2(4) = ", ZZ(4).valuation(2), " :  no")
print("=> E(Q_2) has NO 3-torsion  (contrast y^2 = x^3+1, where (0,+-1) is 3-torsion)")

x^3 - 1 over Q : (X - 1) * (X^2 + X + 1)
-3 mod 8       : 5   so -3 is a square in Q_2 ? False
=> x^2 + x + 1 stays irreducible over Q_2, and E(Q_2)[2] = {O, (1,0)}, r_2 = 1
=> #E(Q_2)/2E(Q_2) = #E(Q_2)[2] * |2|_2^(-1) = 2 * 2 = 4 = 2^(r_2+1)

psi_3          : (3) * x * (x^3 - 4)
   x = 0 needs y^2 = -1 :  i in Q_2 ? False
   x^3 = 4 needs 3 | v_2(4) =  2  :  no
=> E(Q_2) has NO 3-torsion  (contrast y^2 = x^3+1, where (0,+-1) is 3-torsion)


Type $\mathrm{II}$ with $c_2 = 1$ pins the group down completely: $E(\mathbb{Q}_2) = E_0$ (trivial
component group), $E_0/E_1 \cong \tilde E_{\mathrm{ns}}(\mathbb{F}_2) = (\mathbb{F}_2,+)$, and
$E_1 \cong \mathbb{Z}_2$. In particular

> $E(\mathbb{Q}_2)$ is an extension of a $2$-group by a pro-$2$ group, hence **pro-$2$**,

which re-proves the absence of $3$-torsion without touching $\psi_3$. The formal group is
torsion free here because the only candidate, the $2$-torsion point $T = (1,0)$, reduces to the
*smooth* point $(1,0)$ of $\tilde E : y^2 = x^3+1$ over $\mathbb{F}_2$ (whose singular point is
$(0,1)$), so $T \notin E_1$. Being of order $2$ and generating $E_0/E_1$, it splits the filtration:
$$E(\mathbb{Q}_2) \;=\; E_1 \oplus \langle T\rangle \;\cong\; \mathbb{Z}_2 \oplus \mathbb{Z}/2,
\qquad E(\mathbb{Q}_2)/2E(\mathbb{Q}_2) \cong (\mathbb{Z}/2)^2 ,$$
and $2E(\mathbb{Q}_2) = 2E_1 = E_2$. So the four cosets are
$$E_2, \qquad E_1\smallsetminus E_2, \qquad T + E_2, \qquad T + (E_1\smallsetminus E_2),$$
and a generator $Q$ of $E_1 \cong \mathbb{Z}_2$ together with $T$ represents them all.

This shapes the search for $V$ even more sharply than in the $x^3+1$ case: **the global points are
useless.** $E(\mathbb{Q}) = \{\mathcal{O}, T\} \cong \mathbb{Z}/2$ (rank $0$, no $3$-torsion now)
covers only the two cosets $E_2$ and $T + E_2$. Both remaining cosets need a point with irrational
$y$, and one of them — the coset of $Q$ — needs a point of the formal group, i.e. with
$v_2(x) < 0$ (§4).

**The map.** Over $\mathbb{Q}_2$ the Galois action on $E[2]$ fixes $T = (1,0)$ and swaps the two
conjugate points $(\omega,0), (\omega^2,0)$, so $E[2] = \operatorname{Ind}_{\mathbb{Q}_4}^{\mathbb{Q}_2}\mu_2$
is free of rank one over $\mathbb{F}_2[\operatorname{Gal}(\mathbb{Q}_4/\mathbb{Q}_2)]$ and Shapiro gives
$H^1(\mathbb{Q}_2, E[2]) \cong \mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$ — the target is one
field's multiplicative group, not an étale algebra. Concretely: the classical descent map into
$L = \mathbb{Q}_2[x]/(x^3-1) = \mathbb{Q}_2 \times \mathbb{Q}_4$ lands in the norm-one subgroup, and
since $(x-1)\cdot N_{\mathbb{Q}_4/\mathbb{Q}_2}(x - \omega) = x^3-1 = y^2$, the
$\mathbb{Q}_2$-entry is determined mod squares by the $\mathbb{Q}_4$-entry. Nothing is lost by
keeping only
$$\delta(x,y) = x - \omega, \qquad \delta(\mathcal{O}) = 1,
\qquad N_{\mathbb{Q}_4/\mathbb{Q}_2}\big(\delta(x,y)\big) = x^2+x+1 .$$

## 2. The field $\mathbb{Q}_4$, and which classes are squares

In [3]:
K2.<w> = Qq(4, 30)                 # unramified quadratic extension of Q_2; w = zeta_3
print("K2            :", K2)
print("residue field :", K2.residue_field(), "   e =", K2.e(), "  f =", K2.f())
print("w^2 + w + 1   =", w^2 + w + 1)
print("(1 + 2w)^2    =", (1 + 2*w)^2, "     so sqrt(-3) = 1 + 2w")
print()
for c in [-1, 2, 5, -3, 3, 7, 21]:
    print("  [" + str(c).rjust(3) + "] a square in Q_4 ?  " + str(K2(c).is_square()))

K2            : 2-adic Unramified Extension Field in w defined by x^2 + x + 1
residue field : Finite Field in w0 of size 2^2    e = 1   f = 2
w^2 + w + 1   = O(2^30)
(1 + 2w)^2    = 1 + 2^2 + 2^3 + 2^4 + 2^5 + 2^6 + 2^7 + 2^8 + 2^9 + 2^10 + 2^11 + 2^12 + 2^13 + 2^14 + 2^15 + 2^16 + 2^17 + 2^18 + 2^19 + 2^20 + 2^21 + 2^22 + 2^23 + 2^24 + 2^25 + 2^26 + 2^27 + 2^28 + 2^29 + O(2^30)      so sqrt(-3) = 1 + 2w

  [ -1] a square in Q_4 ?  False
  [  2] a square in Q_4 ?  False
  [  5] a square in Q_4 ?  True
  [ -3] a square in Q_4 ?  True
  [  3] a square in Q_4 ?  False
  [  7] a square in Q_4 ?  False
  [ 21] a square in Q_4 ?  True


So $5$ *is* a square in $\mathbb{Q}_4$ (it is unramified, $\mathbb{Q}_4 = \mathbb{Q}_2(\sqrt5)$),
and for $a \in \mathbb{Q}_2^\times$: $a$ is a square in $\mathbb{Q}_4$ exactly when $v_2(a)$ is even
and its unit part is $\equiv 1$ or $5 \pmod 8$. In particular $[3] = [7] = [-1]$ and $[21] = [1]$,
even though $3, 7, 21$ are non-squares in $\mathbb{Q}_2$.

### Why $\#\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2 = 2^{[\mathbb{Q}_4:\mathbb{Q}_2]+2} = 16$

For any finite $K/\mathbb{Q}_2$ of degree $d$ with residue field of size $q$,
$$K^\times \cong \pi^{\mathbb{Z}} \times \mu_{q-1} \times U^{(1)}, \qquad
U^{(1)} \cong \mu_{2^\infty}(K) \times \mathbb{Z}_2^{\,d},$$
the second isomorphism because $\log$ carries $U^{(m)}$ onto $\mathfrak{m}^m \cong (\mathcal{O},+)$
for $m > e/(p-1)$, so $U^{(1)}$ is a finitely generated $\mathbb{Z}_2$-module of rank $d$. Modulo
squares: $\pi^{\mathbb{Z}}$ gives $2$; $\mu_{q-1}$ has **odd** order and gives nothing;
$\mathbb{Z}_2^d$ gives $2^d$; $\mu_{2^\infty}(K) \ni -1$ gives $2$. Total $2^{d+2}$.

The factor $2^d = |2|_K^{-1}$ is the same one that governed $\#E(K)/mE(K)$ in §1, and the other two
are $\#H^0(K,\mu_2)$ and $\#H^2(K,\mu_2) = \#\mathrm{Br}(K)[2]$ — i.e. the count is the local Euler
characteristic $(\#H^0 \cdot \#H^2)/\#H^1 = \|2\|_K = 2^{-d}$ in one line.

For $\mathbb{Q}_4$: $d = 2$, $q = 4$, the odd part is $\mu_3$, and $\mu_{2^\infty}(\mathbb{Q}_4) =
\{\pm1\}$ since $i \notin \mathbb{Q}_4$ ($\mathbb{Q}_2(i)$ is *ramified*). So
$\mathbb{Q}_4^\times \cong 2^{\mathbb{Z}} \times \mu_3 \times \{\pm1\} \times \mathbb{Z}_2^2$ and the
order is $2 \cdot 1 \cdot 2 \cdot 4 = 16$ — which also predicts the shape of a basis: one odd
valuation class, $[-1]$, and two unit classes.

A finite check of the same count, with no structure theory: $(1+4a)^2 = 1 + 8(a + 2a^2)$ and
$a \mapsto a + 2a^2$ is bijective on $\mathcal{O}$ by Hensel, so $1 + 8\mathcal{O}$ consists of
squares and a unit is a square as soon as it is one **mod 8**. Hence
$\mathcal{O}^\times/(\mathcal{O}^\times)^2 = (\mathcal{O}/8\mathcal{O})^\times/\text{squares}$, a
computation in a ring of $64$ elements:

In [4]:
def mul8(u, v):
    "product in O/8O = (Z/8)[w]/(w^2+w+1), elements written as pairs (a,b) = a + b*w"
    (a, b), (c, d) = u, v
    return ((a*c - b*d) % 8, (a*d + b*c - b*d) % 8)

units8   = [(a, b) for a in range(8) for b in range(8) if (a^2 - a*b + b^2) % 2 == 1]
squares8 = sorted(set(mul8(u, u) for u in units8))

print("#(O/8O)    =", 8^2)
print("#(O/8O)^*  =", len(units8))
print("squares    =", len(squares8), " namely", squares8, " = mu_3 * {1, 5}")
print("index      =", len(units8) // len(squares8), " = #O^*/(O^*)^2")
print("times the Z/2 from the valuation:  #Q_4^*/(Q_4^*)^2 =",
      2 * len(units8) // len(squares8))

#(O/8O)    = 64
#(O/8O)^*  = 48
squares    = 6  namely [(0, 1), (0, 5), (1, 0), (3, 3), (5, 0), (7, 7)]  = mu_3 * {1, 5}
index      = 8  = #O^*/(O^*)^2
times the Z/2 from the valuation:  #Q_4^*/(Q_4^*)^2 = 16


## 3. A basis of $\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$, and coordinates

Symbolic bookkeeping happens in the exact field $\mathbb{Q}(\omega)$; squareness is decided in
`K2`. The basis is $B = (2,\ -1,\ 1-\omega,\ -3-\omega)$ — one class of odd valuation, the class
of $-1$, and the two classes that will turn out to be the Kummer image.

In [5]:
KK.<om> = CyclotomicField(3)         # exact home for everything symbolic; om = zeta_3

def to2(z):
    "image of z in Q_4 under om |-> w"
    a, b = z.list()
    return K2(a) + K2(b)*w

def nrm(z):
    "exact norm to Q of a + b*om"
    a, b = z.list()
    return a^2 - a*b + b^2

def is_sq(z):
    "is z a square in Q_4 ?"
    return to2(z).is_square()

def cls(q):
    "the square class of q in Q_2^*, as (v_2(q) mod 2, unit part mod 8)"
    q = QQ(q); v = q.valuation(2); u = q / 2^v
    return (v % 2, ZZ(u.numerator() * ZZ(u.denominator()).inverse_mod(8)) % 8)

B      = [KK(2), KK(-1), 1 - om, -3 - om]
Bnames = ["2", "-1", "1-om", "-3-om"]

def rep(m):
    "the product of the basis elements selected by the bits of m"
    z = KK(1)
    for i in range(4):
        if (m >> i) & 1:
            z *= B[i]
    return z

def coords(z):
    "coordinates of the class of z in the basis B, found by testing squareness"
    for m in range(16):
        if is_sq(z * rep(m)):
            return tuple((m >> i) & 1 for i in range(4))
    raise ValueError("z is not in the span of B")

print("basis:", Bnames)
print()
print("  coords          representative     norm    square?")
for m in range(16):
    z = rep(m)
    c = tuple((m >> i) & 1 for i in range(4))
    print("  " + str(c) + "   " + str(z).rjust(17) + "   "
          + str(nrm(z)).rjust(5) + "    " + str(is_sq(z)))

basis:

 ['2', '-1', '1-om', '-3-om']

  coords          representative     norm    square?
  (0, 0, 0, 0)                   1       1    True
  (1, 0, 0, 0)                   2       4    False
  (0, 1, 0, 0)                  -1       1    False
  (1, 1, 0, 0)                  -2       4    False
  (0, 0, 1, 0)             -om + 1       3    False
  (1, 0, 1, 0)           -2*om + 2      12    False
  (0, 1, 1, 0)              om - 1       3    False
  (1, 1, 1, 0)            2*om - 2      12    False
  (0, 0, 0, 1)             -om - 3       7    False
  (1, 0, 0, 1)           -2*om - 6      28    False
  (0, 1, 0, 1)              om + 3       7    False
  (1, 1, 0, 1)            2*om + 6      28    False
  (0, 0, 1, 1)              om - 4      21    False
  (1, 0, 1, 1)            2*om - 8      84    False
  (0, 1, 1, 1)             -om + 4      21    False
  (1, 1, 1, 1)           -2*om + 8      84    False


Only the empty product is a square, so the $16$ classes are pairwise distinct: $B$ really is an
$\mathbb{F}_2$-basis, and `coords` is well defined on classes.

## 4. The set $V$

Which $x \in \mathbb{Q}_2$ occur? Since $v_2(x^2+x+1) = 0$ whenever $x \in \mathbb{Z}_2$, we get
$v_2(x^3-1) = v_2(x-1)$ for integral $x$, so a point forces $v_2(x-1)$ to be even and positive,
i.e. $x \equiv 1 \pmod 4$; and then $N(x-\omega) = x^2+x+1$ is a **unit**, congruent to $3$ or $7$
mod $8$ according to $x \equiv 1$ or $5 \pmod 8$. An integral $x$ therefore never produces the norm
classes $1$ or $5$.

For $v_2(x) = -2k < 0$ (a formal-group point) write $x^2+x+1 = x^2(1 + x^{-1} + x^{-2})$: the factor
$x^2$ is a square and $v_2(x^{-1}) = 2k \geq 2$, so the unit part is $\equiv 1 + 4 + 16 \equiv 5$
mod $8$ when $k=1$, and $\equiv 1$ mod $8$ when $k \geq 2$. Combined with §1 this identifies the four
cosets on the nose:
$$E_2 \leftrightarrow 1, \qquad E_1\smallsetminus E_2 \leftrightarrow 5, \qquad
T + E_2 \leftrightarrow 3, \qquad T + (E_1\smallsetminus E_2) \leftrightarrow 7 \pmod 8 .$$

In [6]:
Q2 = Qp(2, 60)

print("sampled x = a/4^k with x^3-1 a square in Q_2, sorted by v_2(x):")
print("   v_2(x)   #sampled   classes of N = x^2+x+1  as (v mod 2, unit mod 8)")
for k in range(4):
    found = [QQ(a)/4^k for a in range(-300, 301)
             if (k == 0 or a % 2) and QQ(a) != 4^k and Q2(QQ(a)^3/4^(3*k) - 1).is_square()]
    print("   " + str(-2*k).rjust(6) + str(len(found)).rjust(11) + "        "
          + str(sorted(set(cls(x^2 + x + 1) for x in found))))
print()
print("integral x, by residue mod 8:")
for c in [1, 5]:
    print("   x =", c, "mod 8   =>   x^2+x+1 =", (c^2 + c + 1) % 8, "mod 8")
print("=> the class '5 mod 8' is reached ONLY by points of E_1 \\ E_2, with v_2(x) = -2.")

sampled x = a/4^k with x^3-1 a square in Q_2, sorted by v_2(x):
   v_2(x)   #sampled   classes of N = x^2+x+1  as (v mod 2, unit mod 8)
        0         24        [(0, 3), (0, 7)]
       -2         75        [(0, 5)]
       -4         75        [(0, 1)]
       -6         75        [(0, 1)]

integral x, by residue mod 8:
   x = 1 mod 8   =>   x^2+x+1 = 3 mod 8
   x = 5 mod 8   =>   x^2+x+1 = 7 mod 8
=> the class '5 mod 8' is reached ONLY by points of E_1 \ E_2, with v_2(x) = -2.


So $V$ needs a generator $Q$ of $E_1$, and $v_2(x(Q)) = -2$ is forced. The smallest such $x$ is
$x = 1/4$, with $x^3 - 1 = -63/64 = 9\cdot(-7)/64$:

$-7 \equiv 1 \pmod 8$, so $\sqrt{-7} \in \mathbb{Z}_2^\times$; Hensel pins the root down by three
binary digits, since for $f(Y) = Y^2+7$ one has $|f(3)|_2 = 1/16 < |f'(3)|_2^2 = 1/4$. Take the
root with $y \equiv 3 \pmod 8$. Then
$$Q = \Big(\tfrac14,\ \tfrac38 y\Big), \qquad Q + T = (-3,\ -2y),$$
and the addition is verified **exactly**, in the number field $\mathbb{Q}(\sqrt{-7})$ — which embeds
in $\mathbb{Q}_2$ precisely because $-7$ is a square there.

In [7]:
F.<r> = NumberField(X^2 + 7)                 # r = sqrt(-7)
EF = EllipticCurve(F, [0,0,0,0,-1])
Q, T = EF([QQ(1)/4, 3*r/8]), EF([1, 0])
print("Q     =", Q, "   T =", T, "   order of T:", T.order())
print("Q + T =", Q + T)
print("Q + T == (-3, -2r) ?", Q + T == EF([-3, -2*r]))
print("exact checks: (1/4)^3-1 =", (QQ(1)/4)^3 - 1, "= (3r/8)^2 =", (3*r/8)^2,
      ";  (-3)^3-1 =", (-3)^3 - 1, "= (-2r)^2 =", (-2*r)^2)
print()
print("Q lies in the formal group :  v_2(x(Q)) =", QQ(Q[0]).valuation(2),
      "   v_2(y(Q)) =", QQ(3*QQ(1)/8).valuation(2), "  (y(Q) = (3/8)*r, r a unit)")
print("2Q =", 2*Q, "   v_2(x(2Q)) =", QQ((2*Q)[0]).valuation(2),
      "   => 2Q in E_2, so Q generates E_1 = Z_2")
print("Q+T has integral x, as it must: it lies outside E_1.")

Q     = (1/4 : 3/8*r : 1)    T = (1 : 0 : 1)    order of T: 2
Q + T = (-3 : -2*r : 1)
Q + T == (-3, -2r) ? True
exact checks: (1/4)^3-1 = -63/64 = (3r/8)^2 = -63/64 ;  (-3)^3-1 = -28 = (-2r)^2 = -28

Q lies in the formal group :  v_2(x(Q)) = -2    v_2(y(Q)) = -3   (y(Q) = (3/8)*r, r a unit)
2Q = (-57/112 : -1261/3136*r : 1)    v_2(x(2Q)) = -4    => 2Q in E_2, so Q generates E_1 = Z_2
Q+T has integral x, as it must: it lies outside E_1.


In [8]:
Z2 = Zp(2, 40)
y  = Z2(-7).sqrt()
if y.lift() % 8 != 3:
    y = -y                                   # the root that is 3 mod 8

print("y            =", y)
print("y^2 + 7      =", y^2 + 7)
print("y mod 8      =", y.lift() % 8, "   (this alone determines y, by Hensel)")
print("y mod 2^20   =", y.lift() % 2^20)
print("(3/8)y       =", 3*y/8)
print("-2y mod 2^20 =", (-2*y).lift() % 2^20)
print()
print("V = { O,  T = (1, 0),  Q = (1/4, (3/8)y),  Q+T = (-3, -2y) }")

y            = 1 + 2 + 2^3 + 2^6 + 2^8 + 2^9 + 2^10 + 2^11 + 2^12 + 2^13 + 2^16 + 2^17 + 2^18 + 2^21 + 2^22 + 2^24 + 2^25 + 2^29 + 2^30 + 2^34 + 2^35 + 2^36 + O(2^39)
y^2 + 7      = O(2^40)
y mod 8      = 3    (this alone determines y, by Hensel)
y mod 2^20   = 474955
(3/8)y       = 2^-3 + 2^2 + 2^3 + 2^4 + 2^5 + 2^7 + 2^8 + 2^9 + 2^10 + 2^12 + 2^13 + 2^15 + 2^17 + 2^18 + 2^22 + 2^24 + 2^26 + 2^29 + 2^31 + 2^33 + 2^35 + O(2^36)
-2y mod 2^20 = 98666

V = { O,  T = (1, 0),  Q = (1/4, (3/8)y),  Q+T = (-3, -2y) }


**On precision.** Every $x$-coordinate in $V$ is *rational*, so the Kummer classes below are exact —
no truncation enters $\delta$ at all. The $2$-adic approximation is only ever used to name the point,
and even the sign of $y$ is immaterial, since $-P \equiv P$ modulo $2E(\mathbb{Q}_2)$ and $\delta$
sees only $x$.

## 5. The image

In [9]:
pts = [("O", None), ("T = (1,0)", 1), ("Q = (1/4,3y/8)", QQ(1)/4), ("Q+T = (-3,-2y)", -3)]

print("point".rjust(16) + " " + "x".rjust(5) + "   "
      + "delta = x - om".rjust(16) + " " + "N".rjust(6) + " "
      + "class of N".rjust(11) + "   coords")
for name, x in pts:
    z = KK(1) if x is None else KK(x) - om
    print(name.rjust(16) + " " + ("-" if x is None else str(x)).rjust(5) + "   "
          + str(z).rjust(16) + " " + str(nrm(z)).rjust(6) + " "
          + str(cls(nrm(z))).rjust(11) + "   " + str(coords(z)))

           point     x     delta = x - om      N  class of N   coords
               O     -                  1      1      (0, 1)   (0, 0, 0, 0)
       T = (1,0)     1            -om + 1      3      (0, 3)   (0, 0, 1, 0)
  Q = (1/4,3y/8)   1/4          -om + 1/4  21/16      (0, 5)   (0, 0, 1, 1)
  Q+T = (-3,-2y)    -3            -om - 3      7      (0, 7)   (0, 0, 0, 1)


**Theorem.** $V$ is a complete set of representatives for $E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$, and
$$\operatorname{Im}(\delta) = \{1,\ 1-\omega,\ \tfrac14-\omega,\ -3-\omega\}\cdot(\mathbb{Q}_4^\times)^2
= \big\langle [1-\omega],\ [-3-\omega]\big\rangle \cong (\mathbb{Z}/2)^2 .$$

*Proof.* A square in $\mathbb{Q}_4$ has square norm in $\mathbb{Q}_2$. The four norms are
$1,\ 3,\ 21/16,\ 7 \equiv 1, 3, 5, 7 \pmod 8$, hence lie in four different classes of
$\mathbb{Q}_2^\times/(\mathbb{Q}_2^\times)^2$; so the four values of $\delta$ lie in four different
classes. As $\delta$ is injective on $E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$ and that group has order $4$,
the four points of $V$ represent its four cosets, and their $\delta$-values are the whole image.
$\blacksquare$

Since $4$ is a square, $\tfrac14 - \omega \sim 1 - 4\omega \sim \omega - 4$ — the last being the
product $[1-\omega]\cdot[-3-\omega]$, as the homomorphism property demands. As in the $x^3+1$ case
the norm map is *injective* on the image, carrying it isomorphically onto
$\mathbb{Z}_2^\times/(\mathbb{Z}_2^\times)^2$.

In [10]:
zT, zQ, zQT = 1 - om, QQ(1)/4 - om, -3 - om

# 4 is a square, so delta(Q) has the integral representative 4*(1/4 - om) = 1 - 4om ~ om - 4
print("4*(1/4 - om)            =", 4*zQ, "        [1/4-om] == [om-4] ?", is_sq(zQ*(om - 4)))
print()
# delta is a homomorphism:  delta(T) * delta(Q) = delta(Q+T)
print("(1-om)(1-4om)           =", zT*(1 - 4*om), "  = -3*(1+3om)")
print("same class as -3-om ?   ", is_sq(zT*zQ*zQT), "  [the product of all three is a square]")
print()
# the class of -1 must NOT be in the image: x = 0 would need y^2 = -1
print("delta would be -om at x = 0, of class [-1] =", coords(-om),
      "   but x = 0 needs i in Q_2 :", Qp(2,20)(-1).is_square())
print("[-1] in the image ?     ", coords(KK(-1)) in [coords(z) for z in [KK(1), zT, zQ, zQT]])

4*(1/4 - om)            = -4*om + 1         [1/4-om] == [om-4] ? True

(1-om)(1-4om)           = -9*om - 3   = -3*(1+3om)
same class as -3-om ?    True   [the product of all three is a square]

delta would be -om at x = 0, of class [-1] = (0, 1, 0, 0)    but x = 0 needs i in Q_2 : False
[-1] in the image ?      False


## 6. An independent brute-force scan

Forget the theory: sample $x \in \mathbb{Q}$ (dense in $\mathbb{Q}_2$) with $x^3-1$ a square in
$\mathbb{Q}_2$ — every such $x$ gives a genuine point of $E(\mathbb{Q}_2)$ — and record the class of
$x - \omega$. Exactly four classes should appear, the four above.

In [11]:
seen, count = {}, 0

for k in range(7):                            # x of valuation 0, -2, -4, ..., -12
    for a in range(-400, 401):
        if k > 0 and a % 2 == 0:
            continue
        x = QQ(a) / 4^k
        v = x^3 - 1
        if v == 0 or not Q2(v).is_square():
            continue
        count += 1
        seen.setdefault(coords(KK(x) - om), x)

print("points sampled           :", count)
print("distinct classes reached :", len(seen))
for c in sorted(seen):
    print("   ", c, "  first seen at x =", seen[c])
print()
byk = {}
for k in range(7):
    for a in range(-400, 401):
        if k > 0 and a % 2 == 0:
            continue
        x = QQ(a) / 4^k
        if x^3 - 1 == 0 or not Q2(x^3 - 1).is_square():
            continue
        byk.setdefault(-2*k, set()).add(coords(KK(x) - om))
for v in sorted(byk, reverse=True):
    print("   v_2(x) =", str(v).rjust(3), " classes:", sorted(byk[v]))
print("=> integral x reaches only the classes of T and Q+T; the class of Q needs v_2(x) = -2,")
print("   and the trivial class 2E = E_2 is reached only from v_2(x) <= -4.")

points sampled           : 633
distinct classes reached : 4
    (0, 0, 0, 0)   first seen at x = -399/16
    (0, 0, 0, 1)   first seen at x = -387
    (0, 0, 1, 0)   first seen at x = -335
    (0, 0, 1, 1)   first seen at x = -399/4



   v_2(x) =   0  classes: [(0, 0, 0, 1), (0, 0, 1, 0)]
   v_2(x) =  -2  classes: [(0, 0, 1, 1)]
   v_2(x) =  -4  classes: [(0, 0, 0, 0)]
   v_2(x) =  -6  classes: [(0, 0, 0, 0)]
   v_2(x) =  -8  classes: [(0, 0, 0, 0)]
   v_2(x) = -10  classes: [(0, 0, 0, 0)]
   v_2(x) = -12  classes: [(0, 0, 0, 0)]
=> integral x reaches only the classes of T and Q+T; the class of Q needs v_2(x) = -2,
   and the trivial class 2E = E_2 is reached only from v_2(x) <= -4.


## 7. Where the image sits: duality, and a twist that is easy to get wrong

$\#H^1(\mathbb{Q}_2, E[2]) = 16$, so local Tate duality forces the image to be **maximal isotropic**
of order $4$. But the pairing that does this is *not* the Hilbert symbol of $\mathbb{Q}_4$: the Weil
pairing on $E[2] = \operatorname{Ind}\mu_2$ is the standard pairing of the induced module *composed
with the swap* of the two conjugate points, so under Shapiro the Tate pairing becomes the Frobenius
twist $(a,b) \mapsto (a, \sigma b)_{\mathbb{Q}_4}$.

Hilbert symbols of $\mathbb{Q}_4$ are computed in $\mathbb{Q}(\omega)$ at its prime above $2$, which
is inert — so that completion *is* $\mathbb{Q}_4$.

In [12]:
P2 = KK.primes_above(2)[0]
print("prime above 2 :", P2, "   e =", P2.ramification_index(), "  f =", P2.residue_class_degree())

def hs(u, v):
    "Hilbert symbol of Q_4"
    return KK.hilbert_symbol(u, v, P2)

def sig(z):
    "the Frobenius of Q_4/Q_2:  om |-> om^2"
    a, b = z.list()
    return a + b*om^2

im = [KK(1), 1 - om, om - 4, -3 - om]        # om-4 ~ 1/4-om, an integral representative
print("sigma(1-om) =", sig(1-om), "    sigma(-3-om) =", sig(-3-om))
print()
print("plain    ((u_i, u_j))       ="); show(matrix(4, 4, lambda i, j: hs(im[i], im[j])))
print("twisted  ((u_i, sigma u_j)) ="); show(matrix(4, 4, lambda i, j: hs(im[i], sig(im[j]))))

prime above 2 : Fractional ideal (2)    e = 1   f = 2
sigma(1-om) = om + 2     sigma(-3-om) = om - 2

plain    ((u_i, u_j))       =


[ 1  1  1  1]
[ 1 -1  1 -1]
[ 1  1  1  1]
[ 1 -1  1 -1]

twisted  ((u_i, sigma u_j)) =


[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]

In [13]:
# the annihilator of the image under the twisted pairing
ann = [rep(m) for m in range(16)
       if hs(rep(m), sig(1 - om)) == 1 and hs(rep(m), sig(-3 - om)) == 1]

print("twisted annihilator :", len(ann), "classes:", ann)
print("equals the image ?  ", sorted(coords(z) for z in ann) == sorted(coords(u) for u in im))
print()
# the twisted form is alternating, so 'maximal isotropic' means Lagrangian in a symplectic F_2^4
print("(z, sigma z) = 1 for all 16 classes ?",
      all(hs(rep(m), sig(rep(m))) == 1 for m in range(16)), " => the form is alternating")
print("number of maximal isotropic (Lagrangian) subgroups of order 4 :",
      len(set(frozenset([0, m, n, m ^^ n]) for m in range(1,16) for n in range(1,16)
              if m != n and hs(rep(m), sig(rep(n))) == 1)))
print()
# position relative to the unramified classes H_ur = <-1, 1-om, -3-om>, of order 8
print("all four classes are unit classes (even though the reduction at 2 is additive):",
      all(to2(u).valuation() % 2 == 0 for u in im))
print("(-1, sigma(1-om)) =", hs(-1, sig(1-om)),
      "  so [-1] is NOT in the image, and Im(delta) = { z in H_ur : (z, sigma(1-om)) = 1 }")

twisted annihilator : 4 classes: [1, -om + 1, -om - 3, om - 4]
equals the image ?   True

(z, sigma z) = 1 for all 16 classes ? True  => the form is alternating
number of maximal isotropic (Lagrangian) subgroups of order 4 : 15

all four classes are unit classes (even though the reduction at 2 is additive): True
(-1, sigma(1-om)) = -1   so [-1] is NOT in the image, and Im(delta) = { z in H_ur : (z, sigma(1-om)) = 1 }


The plain symbol is **not** trivial on the image — already $(u,u)_{\mathbb{Q}_4} = -1$ for
$u = 1-\omega$ — while the twisted one vanishes identically and its annihilator is the image itself.
So the image is maximal isotropic on the nose, and the swap is not bookkeeping: it is what makes
duality come out.

## 8. Comparison with $y^2 = x^3+1$: the twist by $-1$ conjugates the image

$E' : y^2 = x^3+1$ and $E : y^2 = x^3-1$ are quadratic twists by $-1$, and $[-1] \in \operatorname{Aut}(E')$
acts trivially on $2$-torsion — so $E'[2]$ and $E[2]$ are the *same* $\operatorname{Gal}$-module and both
Kummer images live in the same group $\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$, as two of its
maximal isotropic subgroups. The canonical identification is $\phi : E' \to E$, $(x,y)\mapsto(-x, iy)$,
defined over $\mathbb{Q}_2(i)$ but Galois-equivariant on $2$-torsion; it sends the distinguished root
$\zeta_6 = 1+\omega$ of $x^2-x+1$ to $-\zeta_6 = \omega^2$ — **not** to $\omega$.

So the honest comparison is between $\operatorname{Im}(\delta_{E'})$, computed with $\zeta_6$, and
$\sigma\big(\operatorname{Im}(\delta_E)\big)$, the image here read off at $\omega^2$ instead of $\omega$.

In [14]:
imE  = [KK(1), 1 - om, om - 4, -3 - om]                 # this notebook,   root om
imE2 = [KK(1), -2 - om, -5 - om, -3 - om]               # y^2 = x^3+1,     root zeta_6 = 1+om

print("Im(delta) for y^2 = x^3-1, root om     :", sorted(coords(z) for z in imE))
print("Im(delta) for y^2 = x^3+1, root zeta_6 :", sorted(coords(z) for z in imE2))
print("   naively equal as subgroups ?         ",
      sorted(coords(z) for z in imE) == sorted(coords(z) for z in imE2))
print("   witness:  (-2-om)*(1-om) =", (-2-om)*(1-om), ", a square in Q_4 ?", is_sq((-2-om)*(1-om)))
print("             (-5-om)*(om-4) =", (-5-om)*(om-4), ", a square in Q_4 ?", is_sq((-5-om)*(om-4)))
print()
print("but phi matches zeta_6 with om^2, so compare with the conjugate image:")
print("Im(delta) for y^2 = x^3-1, root om^2   :", sorted(coords(sig(z)) for z in imE))
print("   equal to the x^3+1 image ?           ",
      sorted(coords(sig(z)) for z in imE) == sorted(coords(z) for z in imE2))
print("   still maximal isotropic ?            ",
      all(hs(sig(u), sig(sig(v))) == 1 for u in imE for v in imE))

Im(delta) for y^2 = x^3-1, root om     : [(0, 0, 0, 0), (0, 0, 0, 1), (0, 0, 1, 0), (0, 0, 1, 1)]
Im(delta) for y^2 = x^3+1, root zeta_6 : [(0, 0, 0, 0), (0, 0, 0, 1), (0, 0, 1, 0), (0, 0, 1, 1)]
   naively equal as subgroups ?          True
   witness:  (-2-om)*(1-om) = -3 , a square in Q_4 ? True
             (-5-om)*(om-4) = 21 , a square in Q_4 ? True

but phi matches zeta_6 with om^2, so compare with the conjugate image:
Im(delta) for y^2 = x^3-1, root om^2   : [(0, 0, 0, 0), (0, 0, 1, 1), (0, 1, 0, 1), (0, 1, 1, 0)]
   equal to the x^3+1 image ?            False
   still maximal isotropic ?             True


Both readings are worth having straight:

- with the *naive* matching of names ($\zeta_6 \leftrightarrow \omega$) the two images look
  identical, because $(-2-\omega)(1-\omega) = -3$ and $(-5-\omega)(\omega-4) = 21$ are both squares
  in $\mathbb{Q}_4$;
- under the *canonical* identification $\phi$ ($\zeta_6 \leftrightarrow \omega^2$) they are Frobenius
  conjugates of one another, and genuinely different subgroups — the image here is not
  $\sigma$-stable.

That is exactly what one should expect: twisting by $-1$ is invisible on $E[2]$ but not on the
local condition it cuts out, and the two curves do have different reduction at $2$ (type $\mathrm{IV}$,
$c_2 = 3$ versus type $\mathrm{II}$, $c_2 = 1$).

## Summary

$$V = \Big\{\mathcal{O},\ (1,0),\ \big(\tfrac14,\tfrac38 y\big),\ (-3,-2y)\Big\}, \qquad
\operatorname{Im}(\delta) = \{1,\ 1-\omega,\ \omega-4,\ -3-\omega\} \cdot (\mathbb{Q}_4^\times)^2 .$$

- the image is $\langle [1-\omega], [-3-\omega]\rangle$, the span of the last two vectors of the
  basis $(2,\,-1,\,1-\omega,\,-3-\omega)$ of the $16$-element group
  $\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$;
- the norm map sends it isomorphically onto $\mathbb{Z}_2^\times/(\mathbb{Z}_2^\times)^2$, which is
  what separates the four classes, and the four norm classes $1,5,3,7 \bmod 8$ match the four
  layers $E_2,\ E_1\smallsetminus E_2,\ T+E_2,\ T+(E_1\smallsetminus E_2)$ of the filtration;
- consequently the coset of $Q$ contains **no** point with integral $x$: unlike the $x^3+1$ case,
  $V$ is forced into the formal group, and $E(\mathbb{Q}_2) = E_1\oplus\langle T\rangle$ is pro-$2$;
- it consists of **unit** classes although $E$ has additive reduction at $2$, sitting with index $2$
  in the $8$-element unramified subgroup — which is itself too big to be a local condition;
- it is maximal isotropic for the Frobenius-twisted Hilbert symbol, as local duality demands, and
  the twist by $-1$ moves it to its Frobenius conjugate — a different Lagrangian.

Choosing the other root $\omega^2$ conjugates everything: the image becomes
$\langle[1-\omega^2],[-3-\omega^2]\rangle$. Nothing is ambiguous — $\delta$ and its image are
conjugated together the moment one renames $\omega$ as $\omega^2$.