# The local Kummer image at $p = 2$ for $y^2 = x^3 - 3$

For $E : y^2 = x^3-3$ (curve `972b1`, $j = 0$, CM by $\mathbb{Z}[\zeta_3]$, conductor
$972 = 2^2\cdot 3^5$) we write down an explicit finite set $V \subset E(\mathbb{Q}_2)$ representing
$E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$ and compute its image under the local Kummer map at $2$ inside
$$\mathbb{Q}_4 \;=\; \mathbb{Q}_2(\omega) \;=\; \mathbb{Q}_2(\sqrt{-3}) \;=\; \mathbb{Q}_2(\sqrt 5),$$
the unramified quadratic extension of $\mathbb{Q}_2$.

**The extreme case of the family.** $E(\mathbb{Q})$ is **trivial**: rank $0$ and no torsion. Not one
of the four cosets except $2E(\mathbb{Q}_2)$ contains a rational point, so every element of $V$ other
than $\mathcal{O}$ has to be produced $2$-adically. As for $y^2=x^3+3$, the cubic $x^3-3$ is
irreducible over $\mathbb{Q}$ but splits over $\mathbb{Q}_2$ — every $2$-adic unit is a cube — giving
a local $2$-torsion point
$$T = (\varphi, 0), \qquad \varphi = \sqrt[3]{3} \in \mathbb{Z}_2^\times, \qquad \varphi \equiv 3 \ (8),$$
and $x^2+\varphi x+\varphi^2$ has discriminant $-3\varphi^2$, so again $\mathbb{Q}_2(E[2]) = \mathbb{Q}_4$,
$E[2] = \operatorname{Ind}_{\mathbb{Q}_4}^{\mathbb{Q}_2}\mu_2$, and Shapiro gives
$H^1(\mathbb{Q}_2,E[2]) \cong \mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$, of order $16$, with
$$\delta(x,y) = x - \rho, \qquad \rho = \varphi\,\omega, \qquad
N_{\mathbb{Q}_4/\mathbb{Q}_2}\big(\delta(x,y)\big) = x^2+\varphi x+\varphi^2 .$$
Here $v_2(\varphi - 3) = 3$ **exactly**, which is just enough to replace $\delta$ by $x-3\omega$ modulo
squares (§3) — the bound is tight, unlike the $x^3+3$ case where $v_2(e-5) = 7$ left room to spare.

**The answer.**
$$V = \{\mathcal{O},\ T,\ P,\ Q\}
 = \Big\{\mathcal{O},\ \big(\sqrt[3]{3},\,0\big),\ \big(-9,\ 2\sqrt{-183}\big),\
   \big(\tfrac14,\ \tfrac18\sqrt{-191}\big)\Big\},$$
$$\operatorname{Im}(\delta) = \{1,\ 3-3\omega,\ -9-3\omega,\ \tfrac14-3\omega\}\cdot(\mathbb{Q}_4^\times)^2
 = \big\langle [\omega-1],\, [3+\omega] \big\rangle \subset \mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2 .$$
The four classes are distinct for the usual one-line reason: their norms are $1,\ 27,\ 63,\ 157/16$,
i.e. $1, 3, 7, 5$ mod $8$ — *all four* square classes of $\mathbb{Z}_2^\times$ — and a square has a
square norm.

This is the **Frobenius conjugate** of the subgroup found for $y^2 = x^3\pm 1$ and $y^2 = x^3+3$: since
$3 \equiv 3 \pmod 8$ is *not* a square in $\mathbb{Q}_4$, $[\delta(T)] = [3(1-\omega)] = [\omega-1]$
rather than $[1-\omega]$, and the whole image tips over to the other Lagrangian. §9 closes the family:
$b \in \{1,-1,3,-3\}$ realises all four classes of $b$ mod $8$, hence **all** $\mathbb{Q}_2$-isomorphism
classes of $y^2=x^3+b$ with $b$ a unit, and they fall into two unramified-twist pairs giving exactly
two Lagrangians.

Companions: `local-kummer-p2.ipynb` ($b=1$), `local-kummer-p2-minus.ipynb` ($b=-1$),
`local-kummer-p2-plus3.ipynb` ($b=3$).

## 1. The curve at $2$, and the size of $E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$

In [1]:
E = EllipticCurve([0,0,0,0,-3])             # y^2 = x^3 - 3
print("E             :", E)
print("discriminant  :", E.discriminant(), "=", factor(E.discriminant()))
print("j-invariant   :", E.j_invariant(), "   conductor:", factor(E.conductor()),
      "   label:", E.cremona_label())
print("globally minimal:", E.is_minimal())

ld = E.local_data(2)
print("at p = 2      : Kodaira", ld.kodaira_symbol(),
      "  f =", ld.conductor_valuation(), "  c_2 =", ld.tamagawa_number())
print("E(Q)          : torsion", E.torsion_subgroup().invariants(),
      "  rank", E.rank(), "  =>  E(Q) = { O }")

E             : Elliptic Curve defined by y^2 = x^3 - 3 over Rational Field
discriminant  : -3888 = -1 * 2^4 * 3^5
j-invariant   : 0    conductor: 2^2 * 3^5    label: 972b1
globally minimal: True
at p = 2      : Kodaira IV   f = 2   c_2 = 1
E(Q)          : torsion ()   rank 0   =>  E(Q) = { O }


### $E[2]$ is invisible over $\mathbb{Q}$ but half-visible over $\mathbb{Q}_2$

$\mathbb{Z}_2^\times \cong \mu_2 \times \mathbb{Z}_2$ is a pro-$2$ group and $3$ is invertible in
$\mathbb{Z}_2$, so cubing is an automorphism of $\mathbb{Z}_2^\times$: every $2$-adic unit is a cube.
Hence $x^3-3$ has the root $\varphi = \sqrt[3]{3} \in \mathbb{Z}_2^\times$ although it is irreducible
over $\mathbb{Q}$.

In [2]:
R.<X> = QQ[]
print("x^3 - 3 over Q   :", factor(X^3 - 3), "   irreducible => E[2](Q) = 0")
print("cubing on (Z/8)^*:", {u: (u^3) % 8 for u in [1,3,5,7]}, "  -- a bijection")
print()
Z2 = Zp(2, 60)
ph = Z2(3).nth_root(3)
print("phi = 3^(1/3)    :", ph)
print("phi^3 - 3        :", ph^3 - 3)
print("phi mod 8,16,32  :", ph.lift() % 8, ",", ph.lift() % 16, ",", ph.lift() % 32,
      "     v_2(phi - 3) =", (ph - 3).valuation(), "  (exactly 3)")
print()
S.<Y> = Z2[]
print("(Y-phi)(Y^2+phi*Y+phi^2) - (Y^3-3) =", (Y - ph)*(Y^2 + ph*Y + ph^2) - (Y^3 - 3))
print("disc(x^2+phi*x+phi^2) = phi^2 - 4phi^2 = -3phi^2")
print("-3 a square in Q_2 ?", Qp(2,20)(-3).is_square(),
      "  => the quadratic factor generates Q_4 = Q_2(sqrt(-3))")
print("=> E(Q_2)[2] = {O, T},  T = (phi,0),  r_2 = 1")
print("=> #E(Q_2)/2E(Q_2) = #E(Q_2)[2] * |2|_2^(-1) = 2 * 2 = 4")

x^3 - 3 over Q   : X^3 - 3    irreducible => E[2](Q) = 0
cubing on (Z/8)^*: {1: 1, 3: 3, 5: 5, 7: 7}   -- a bijection

phi = 3^(1/3)    : 1 + 2 + 2^3 + 2^4 + 2^5 + 2^6 + 2^8 + 2^12 + 2^13 + 2^14 + 2^15 + 2^16 + 2^21 + 2^24 + 2^25 + 2^26 + 2^27 + 2^30 + 2^31 + 2^32 + 2^34 + 2^35 + 2^38 + 2^40 + 2^42 + 2^43 + 2^46 + 2^47 + 2^48 + 2^49 + 2^50 + 2^51 + 2^52 + 2^53 + 2^54 + 2^55 + 2^56 + O(2^60)
phi^3 - 3        : O(2^60)
phi mod 8,16,32  : 3 , 11 , 27      v_2(phi - 3) = 3   (exactly 3)

(Y-phi)(Y^2+phi*Y+phi^2) - (Y^3-3) = O(2^60)*Y^3 + O(2^60)*Y^2 + O(2^60)*Y + O(2^60)
disc(x^2+phi*x+phi^2) = phi^2 - 4phi^2 = -3phi^2
-3 a square in Q_2 ? False   => the quadratic factor generates Q_4 = Q_2(sqrt(-3))
=> E(Q_2)[2] = {O, T},  T = (phi,0),  r_2 = 1
=> #E(Q_2)/2E(Q_2) = #E(Q_2)[2] * |2|_2^(-1) = 2 * 2 = 4


The reduction is of type $\mathrm{IV}$ but with $c_2 = 1$ — the same Kodaira type as $y^2=x^3+1$,
where $c_2 = 3$; the unramified twist relating the two (§9) preserves the type and changes the Galois
action on the three components. With $c_2 = 1$ we get $E(\mathbb{Q}_2) = E_0$, and as always
$E_0/E_1 \cong \tilde E_{\mathrm{ns}}(\mathbb{F}_2) = (\mathbb{F}_2,+)$ for additive reduction, with
$E_1 \cong \mathbb{Z}_2$. So $E(\mathbb{Q}_2)$ is **pro-$2$**. The reduction $\tilde E : y^2 = x^3+1$
over $\mathbb{F}_2$ has its singular point at $(0,1)$; since $\varphi$ is a unit, $T = (\varphi,0)$
reduces to the *smooth* point $(1,0)$, so $T \notin E_1$ and, having order $2$ and generating
$E_0/E_1$, splits the filtration:
$$E(\mathbb{Q}_2) \;=\; E_1 \oplus \langle T\rangle \;\cong\; \mathbb{Z}_2 \oplus \mathbb{Z}/2,
\qquad 2E(\mathbb{Q}_2) = 2E_1 = E_2 ,$$
with cosets $E_2$, $E_1\smallsetminus E_2$, $T+E_2$, $T+(E_1\smallsetminus E_2)$.

**Nothing global helps.** $E(\mathbb{Q}) = \{\mathcal{O}\}$, so the rational points reach only the
trivial coset. Every other representative below is genuinely $2$-adic: $T$ has irrational $x$, and
$P$, $Q$ have irrational $y$.

## 2. The field $\mathbb{Q}_4$, and which classes are squares

In [3]:
K2.<w> = Qq(4, 40)                 # unramified quadratic extension of Q_2; w = zeta_3
print("K2            :", K2)
print("residue field :", K2.residue_field(), "   e =", K2.e(), "  f =", K2.f())
print("w^2 + w + 1   =", w^2 + w + 1)
print("(1 + 2w)^2    =", (1 + 2*w)^2 + O(2^10), "  ...   so sqrt(-3) = 1 + 2w")
print()
for c in [-1, 2, 5, -3, 3, 7, 21, 27, 63]:
    print("  [" + str(c).rjust(3) + "] a square in Q_4 ?  " + str(K2(c).is_square()))

K2            :

 2-adic Unramified Extension Field in w defined by x^2 + x + 1
residue field : Finite Field in w0 of size 2^2    e = 1   f = 2
w^2 + w + 1   = O(2^40)
(1 + 2w)^2    = 1 + 2^2 + 2^3 + 2^4 + 2^5 + 2^6 + 2^7 + 2^8 + 2^9 + O(2^10)   ...   so sqrt(-3) = 1 + 2w

  [ -1] a square in Q_4 ?  False
  [  2] a square in Q_4 ?  False
  [  5] a square in Q_4 ?  True
  [ -3] a square in Q_4 ?  True
  [  3] a square in Q_4 ?  False
  [  7] a square in Q_4 ?  False
  [ 21] a square in Q_4 ?  True
  [ 27] a square in Q_4 ?  False
  [ 63] a square in Q_4 ?  False


A unit of $\mathbb{Q}_4$ is a square as soon as it is one **mod $8$**: $(1+4a)^2 = 1+8(a+2a^2)$ and
$a \mapsto a+2a^2$ is bijective on $\mathcal{O}$ by Hensel, so $1+8\mathcal{O} \subset
(\mathcal{O}^\times)^2$. That single fact is used twice below — once to count
$\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$, and once (in §3) to replace the irrational $\varphi$ by $3$.

For $a \in \mathbb{Q}_2^\times$: $a$ is a square in $\mathbb{Q}_4$ exactly when $v_2(a)$ is even and
its unit part is $\equiv 1$ or $5 \pmod 8$. Note in particular that $\mathbf{3}$ **is not a square**
in $\mathbb{Q}_4$, and $[3] = [-1]$ because $-3$ is one. That single sign is what moves this curve's
image to the other Lagrangian (§6).

### Why $\#\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2 = 2^{[\mathbb{Q}_4:\mathbb{Q}_2]+2} = 16$

For any finite $K/\mathbb{Q}_2$ of degree $d$ with residue field of size $q$,
$$K^\times \cong \pi^{\mathbb{Z}} \times \mu_{q-1} \times U^{(1)}, \qquad
U^{(1)} \cong \mu_{2^\infty}(K) \times \mathbb{Z}_2^{\,d},$$
the second isomorphism because $\log$ carries $U^{(m)}$ onto $\mathfrak{m}^m \cong (\mathcal{O},+)$
for $m > e/(p-1)$. Modulo squares: $\pi^{\mathbb{Z}}$ gives $2$; $\mu_{q-1}$ has **odd** order and
gives nothing; $\mathbb{Z}_2^d$ gives $2^d$; $\mu_{2^\infty}(K) \ni -1$ gives $2$. Total $2^{d+2}$.

For $\mathbb{Q}_4$: $d = 2$, $q = 4$, odd part $\mu_3$, and $\mu_{2^\infty}(\mathbb{Q}_4) = \{\pm1\}$
since $\mathbb{Q}_2(i)$ is *ramified*. So the order is $16$, and a basis should consist of one class
of odd valuation, $[-1]$, and two unit classes. The finite check, in a ring of $64$ elements:

In [4]:
def mul8(u, v):
    "product in O/8O = (Z/8)[w]/(w^2+w+1), elements written as pairs (a,b) = a + b*w"
    (a, b), (c, d) = u, v
    return ((a*c - b*d) % 8, (a*d + b*c - b*d) % 8)

units8   = [(a, b) for a in range(8) for b in range(8) if (a^2 - a*b + b^2) % 2 == 1]
squares8 = sorted(set(mul8(u, u) for u in units8))

print("#(O/8O)^*  =", len(units8), "   squares:", len(squares8), squares8, " = mu_3 * {1, 5}")
print("index      =", len(units8) // len(squares8), " = #O^*/(O^*)^2")
print("times the Z/2 from the valuation:  #Q_4^*/(Q_4^*)^2 =",
      2 * len(units8) // len(squares8))

#(O/8O)^*  = 48    squares: 6 [(0, 1), (0, 5), (1, 0), (3, 3), (5, 0), (7, 7)]  = mu_3 * {1, 5}
index      = 8  = #O^*/(O^*)^2
times the Z/2 from the valuation:  #Q_4^*/(Q_4^*)^2 = 16


## 3. Getting rid of $\varphi$: the substitution $x - \varphi\omega \;\rightsquigarrow\; x - 3\omega$

Write elements of $\mathbb{Q}_4$ as $\alpha + \beta\omega$ with $\alpha,\beta \in \mathbb{Q}_2$;
since $\{1,\omega\}$ is an integral basis, $v(\alpha+\beta\omega) = \min(v\alpha, v\beta)$.

> **Lemma.** Let $z = \alpha+\beta\omega \neq 0$ and $\tilde z = \tilde\alpha + \tilde\beta\omega$ with
> $\min\big(v(\alpha-\tilde\alpha),\, v(\beta-\tilde\beta)\big) \geq v(z) + 3$. Then
> $\tilde z / z \in 1 + 8\mathcal{O}$, hence $[\tilde z] = [z]$ in $\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$.
>
> *Proof.* $\tilde z/z = 1 + (\tilde z - z)/z$ and $v\big((\tilde z-z)/z\big) \geq 3$; now
> $1+8\mathcal{O}$ consists of squares (§2). $\square$

Apply it to $z = \delta(x,y) = x - \varphi\omega$ with $x \in \mathbb{Q}_2$: here
$v(z) = \min(v(x), 0) \leq 0$, so the hypothesis reduces to $v(\varphi-3) \geq 3$ — which holds, with
**equality**. So the margin is exactly zero and the substitution still goes through: for every
$x \in \mathbb{Q}_2$ and every rational $\tilde x \equiv x \pmod 8$,
$$[\,x - \varphi\omega\,] = [\,\tilde x - 3\omega\,] .$$
At the $2$-torsion point, $x = \varphi$ itself: $\delta(T) = \varphi(1-\omega)$, and taking
$\tilde x = 3$ gives $\tilde z - z = (\varphi-3)(1-\omega)$ of valuation $3$ while $v(z) = 0$, so
$[\delta(T)] = [3-3\omega] = [3]\cdot[1-\omega] = [\omega-1]$ — the last step because $3$ is **not**
a square in $\mathbb{Q}_4$, but $-3$ is, so $[3] = [-1]$.

In [5]:
phK = K2(ph)
print("v_2(phi - 3) =", (ph - 3).valuation(), "  -- exactly the bound the lemma needs")
print()
print("checking [x - phi*w] == [x - 3*w] for x = a/4^k, a in [-60,60], k = 0,1,2 :")
bad = [(QQ(a)/4^k) for k in range(3) for a in range(-60, 61)
       if K2(QQ(a)/4^k) - phK*w != 0
       and not ((K2(QQ(a)/4^k) - phK*w) * (K2(QQ(a)/4^k) - 3*w)).is_square()]
print("   failures:", bad)
print()
print("and at the 2-torsion point itself, x = phi:")
print("   [phi - phi*w] == [3 - 3*w] ?", ((phK - phK*w) * (K2(3) - 3*w)).is_square())
print("   [3 - 3*w]     == [w - 1]   ?", ((K2(3) - 3*w) * (w - 1)).is_square(),
      "   (because 3 is NOT a square in Q_4, but -3 is)")

v_2(phi - 3) = 3   -- exactly the bound the lemma needs

checking [x - phi*w] == [x - 3*w] for x = a/4^k, a in [-60,60], k = 0,1,2 :
   failures: []

and at the 2-torsion point itself, x = phi:
   [phi - phi*w] == [3 - 3*w] ? True
   [3 - 3*w]     == [w - 1]   ? True    (because 3 is NOT a square in Q_4, but -3 is)


## 4. A basis of $\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$, and coordinates

The same basis $B = (2,\ -1,\ 1-\omega,\ -3-\omega)$ as in the companion notebooks, so that all four
images can be compared literally in §9.

In [6]:
KK.<om> = CyclotomicField(3)         # exact home for everything symbolic; om = zeta_3

def to2(z):
    "image of z in Q_4 under om |-> w"
    a, b = z.list()
    return K2(a) + K2(b)*w

def nrm(z):
    "exact norm to Q of a + b*om"
    a, b = z.list()
    return a^2 - a*b + b^2

def is_sq(z):
    "is z a square in Q_4 ?"
    return to2(z).is_square()

def cls(q):
    "the square class of q in Q_2^*, as (v_2(q) mod 2, unit part mod 8)"
    q = QQ(q); v = q.valuation(2); u = q / 2^v
    return (v % 2, ZZ(u.numerator() * ZZ(u.denominator()).inverse_mod(8)) % 8)

B      = [KK(2), KK(-1), 1 - om, -3 - om]
Bnames = ["2", "-1", "1-om", "-3-om"]

def rep(m):
    "the product of the basis elements selected by the bits of m"
    z = KK(1)
    for i in range(4):
        if (m >> i) & 1:
            z *= B[i]
    return z

def coords(z):
    "coordinates of the class of z in the basis B, found by testing squareness"
    for m in range(16):
        if is_sq(z * rep(m)):
            return tuple((m >> i) & 1 for i in range(4))
    raise ValueError("z is not in the span of B")

print("basis:", Bnames)
print()
print("  coords          representative     norm    square?")
for m in range(16):
    z = rep(m)
    c = tuple((m >> i) & 1 for i in range(4))
    print("  " + str(c) + "   " + str(z).rjust(17) + "   "
          + str(nrm(z)).rjust(5) + "    " + str(is_sq(z)))

basis: ['2', '-1', '1-om', '-3-om']

  coords          representative     norm    square?
  (0, 0, 0, 0)                   1       1    True
  (1, 0, 0, 0)                   2       4    False
  (0, 1, 0, 0)                  -1       1    False
  (1, 1, 0, 0)                  -2       4    False
  (0, 0, 1, 0)             -om + 1       3    False
  (1, 0, 1, 0)           -2*om + 2      12    False
  (0, 1, 1, 0)              om - 1       3    False
  (1, 1, 1, 0)            2*om - 2      12    False
  (0, 0, 0, 1)             -om - 3       7    False
  (1, 0, 0, 1)           -2*om - 6      28    False
  (0, 1, 0, 1)              om + 3       7    False
  (1, 1, 0, 1)            2*om + 6      28    False
  (0, 0, 1, 1)              om - 4      21    False
  (1, 0, 1, 1)            2*om - 8      84    False
  (0, 1, 1, 1)             -om + 4      21    False
  (1, 1, 1, 1)           -2*om + 8      84    False


Only the empty product is a square, so $B$ really is an $\mathbb{F}_2$-basis and `coords` is well
defined on classes.

## 5. The set $V$

Which $x$ occur? For $x \in \mathbb{Z}_2$ the norm $x^2+\varphi x+\varphi^2$ is a **unit** (mod $2$ it is
$x^2+x+1 \equiv 1$), so $v_2(x^3-3) = v_2(x-\varphi)$. An even $x$ gives $x^3-3 \equiv 5 \pmod 8$,
never a square; so $x$ is odd and $v_2(x-\varphi)$ must be even and positive, i.e.
$x \equiv \varphi \equiv 3 \pmod 4$. Substituting $\varphi \rightsquigarrow 3$, the norm class is then
read off from $x$ mod $8$:
$$x \equiv 3 \ (8) \Rightarrow x^2+3x+9 \equiv 3 \ (8), \qquad
  x \equiv 7 \ (8) \Rightarrow x^2+3x+9 \equiv 7 \ (8) .$$
So an integral $x$ never gives the norm classes $1$ or $5$. For $v_2(x) = -2k < 0$ write
$x^2+\varphi x+\varphi^2 = x^2(1 + \varphi x^{-1} + \varphi^2x^{-2})$: the unit part is
$\equiv 1+4 \equiv 5 \pmod 8$ when $k = 1$ and $\equiv 1 \pmod 8$ when $k \geq 2$. Together with §1
this labels the four cosets:
$$E_2 \leftrightarrow 1, \qquad E_1\smallsetminus E_2 \leftrightarrow 5, \qquad
T + E_2 \leftrightarrow 3, \qquad T + (E_1\smallsetminus E_2) \leftrightarrow 7 \pmod 8 .$$

In [7]:
Q2 = Qp(2, 60)

print("sampled x = a/4^k with x^3-3 a square in Q_2, sorted by v_2(x):")
print("   v_2(x)   #sampled   classes of N = x^2+3x+9   as (v mod 2, unit mod 8)")
for k in range(4):
    found = [QQ(a)/4^k for a in range(-300, 301)
             if (k == 0 or a % 2) and Q2(QQ(a)^3/4^(3*k) - 3).is_square()]
    print("   " + str(-2*k).rjust(6) + str(len(found)).rjust(11) + "         "
          + str(sorted(set(cls(x^2 + 3*x + 9) for x in found))))
print()
print("integral x, by residue mod 8:")
for c in [3, 7]:
    print("   x =", c, "mod 8   =>   x^2+3x+9 =", (c^2 + 3*c + 9) % 8, "mod 8")
print()
print("smallest integral x giving a point:",
      sorted([a for a in range(-200, 201) if Q2(a^3 - 3).is_square()], key=abs)[:6])

sampled x = a/4^k with x^3-3 a square in Q_2, sorted by v_2(x):
   v_2(x)   #sampled   classes of N = x^2+3x+9   as (v mod 2, unit mod 8)
        0         25         [(0, 3), (0, 7)]
       -2         75         [(0, 5)]
       -4         75         [(0, 1)]
       -6         75         [(0, 1)]

integral x, by residue mod 8:
   x = 3 mod 8   =>   x^2+3x+9 = 3 mod 8
   x = 7 mod 8   =>   x^2+3x+9 = 7 mod 8



smallest integral x giving a point:

 [-9, 23, -41, 43, 55, 59]


So the three non-trivial cosets are reached by
$$T = (\varphi,0)\ \ [x \equiv 3\ (8)], \qquad
P = \big(-9,\ 2\sqrt{-183}\big)\ \ [x \equiv 7\ (8)], \qquad
Q = \Big(\tfrac14,\ \tfrac18\sqrt{-191}\Big)\ \ [v_2(x) = -2],$$
using $(-9)^3-3 = -732 = 4\cdot(-183)$ with $-183 \equiv 1 \pmod 8$, and
$\big(\tfrac14\big)^3-3 = -\tfrac{191}{64}$ with $-191 \equiv 1 \pmod 8$. So $Q \in E_1(\mathbb{Q}_2)$
generates $E_1 \cong \mathbb{Z}_2$, and none of $T, P, Q$ is rational.

That $Q$ represents the coset of $T+P$ is checked **exactly**, in $\mathbb{Q}(\sqrt[3]{3},\sqrt{-183})$
where $T$ and $P$ both become rational:

In [8]:
print("(-9)^3 - 3 =", (-9)^3 - 3, "= 4 *", ((-9)^3-3)//4, ";  -183 mod 8 =", (-183) % 8,
      ";  a square in Q_2 ?", Q2((-9)^3 - 3).is_square())
print("(1/4)^3 - 3 =", QQ(1)/64 - 3, ";  -191 mod 8 =", (-191) % 8,
      ";  a square in Q_2 ?", Q2(QQ(1)/64 - 3).is_square())
print()
L.<phi> = NumberField(X^3 - 3)               # phi = cube root of 3, phi |-> varphi in Q_2
SL.<Y>  = L[]
M.<sr>  = L.extension(Y^2 + 183)             # sr = sqrt(-183)
EM = EllipticCurve(M, [0,0,0,0,-3])
TM, PM = EM([phi, 0]), EM([-9, 2*sr])
S = TM + PM
print("T =", TM, "   P =", PM)
print("T + P =", S)
print("on the curve ?", S[1]^2 == S[0]^3 - 3, "   x(T+P) lies in Q(3^(1/3)) ?", S[0].list()[1] == 0)

srK = K2(Z2(-183).sqrt())
def embL(z):  return sum(K2(z.list()[i]) * phK^i for i in range(3))
def embM(z):  return embL(z.list()[0]) + embL(z.list()[1]) * srK
xS = embM(S[0])
print()
print("v_2(x(T+P)) =", xS.valuation(), "  => T+P lies in E_1, as its norm class 5 demands")
print("[x(T+P) - phi*w] == [1/4 - 3*w] ?", ((xS - phK*w) * (K2(QQ(1)/4) - 3*w)).is_square())
print("=> Q = T + P  in E(Q_2)/2E(Q_2)")

(-9)^3 - 3 = -732 = 4 * -183 ;  -183 mod 8 = 1 ;  a square in Q_2 ? True
(1/4)^3 - 3 = -191/64 ;  -191 mod 8 = 1 ;  a square in Q_2 ? True

T = (phi : 0 : 1)    P = (-9 : 2*sr : 1)
T + P = (-81/244*phi^2 + 241/244*phi + 27/244 : (-2169/29768*phi^2 - 243/29768*phi + 1455/29768)*sr : 1)
on the curve ? True    x(T+P) lies in Q(3^(1/3)) ? True

v_2(x(T+P)) = -2   => T+P lies in E_1, as its norm class 5 demands
[x(T+P) - phi*w] == [1/4 - 3*w] ? True
=> Q = T + P  in E(Q_2)/2E(Q_2)


## 6. The image

In [9]:
pts = [("O", None, None), ("T = (phi,0)", "phi", 3),
       ("P = (-9,2sqrt(-183))", "-9", -9), ("Q = (1/4,sqrt(-191)/8)", "1/4", QQ(1)/4)]

print("point".rjust(23) + " " + "x".rjust(4) + "   "
      + "delta ~ xt - 3om".rjust(17) + " " + "N".rjust(7) + " "
      + "class of N".rjust(11) + "   coords")
for name, xname, xt in pts:
    z = KK(1) if xt is None else KK(xt) - 3*om
    print(name.rjust(23) + " " + (xname or "-").rjust(4) + "   "
          + str(z).rjust(17) + " " + str(nrm(z)).rjust(7) + " "
          + str(cls(nrm(z))).rjust(11) + "   " + str(coords(z)))

                  point    x    delta ~ xt - 3om       N  class of N   coords
                      O    -                   1       1      (0, 1)   (0, 0, 0, 0)
            T = (phi,0)  phi           -3*om + 3      27      (0, 3)   (0, 1, 1, 0)
   P = (-9,2sqrt(-183))   -9           -3*om - 9      63      (0, 7)   (0, 1, 0, 1)
 Q = (1/4,sqrt(-191)/8)  1/4         -3*om + 1/4  157/16      (0, 5)   (0, 0, 1, 1)


**Theorem.** $V = \{\mathcal{O}, T, P, Q\}$ is a complete set of representatives for
$E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$, and
$$\operatorname{Im}(\delta) = \{1,\ 3-3\omega,\ -9-3\omega,\ \tfrac14-3\omega\}\cdot(\mathbb{Q}_4^\times)^2
= \big\langle [\omega-1],\ [3+\omega]\big\rangle \cong (\mathbb{Z}/2)^2 .$$

*Proof.* A square in $\mathbb{Q}_4$ has square norm in $\mathbb{Q}_2$. The four norms are
$1,\ 27,\ 63,\ 157/16 \equiv 1, 3, 7, 5 \pmod 8$, four different classes of
$\mathbb{Q}_2^\times/(\mathbb{Q}_2^\times)^2$; so the four values of $\delta$ lie in four different
classes. As $\delta$ is injective on $E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$, of order $4$, the four
points represent all four cosets and their $\delta$-values are the whole image. $\blacksquare$

The pretty representatives are $[3-3\omega] = [\omega-1]$, $[-9-3\omega] = [3+\omega]$ (because
$-3$ is a square) and $[\tfrac14-3\omega] = [\omega-4]$. Note how the first two differ from the
$y^2=x^3\pm1,\,x^3+3$ answers by exactly a factor $[-1]$: that is the whole difference between the
two Lagrangians.

In [10]:
print("[3-3om]    == [om-1] ?", is_sq((3-3*om)*(om-1)), "   (3 is not a square, but -3 is)")
print("[-9-3om]   == [3+om] ?", is_sq((-9-3*om)*(3+om)), "   since -9-3om = -3*(3+om) and -3 is a square")
print("[1/4-3om]  == [om-4] ?", is_sq((QQ(1)/4-3*om)*(om-4)))
print()
print("coords:  [om-1]", coords(om-1), "  [3+om]", coords(3+om), "  [om-4]", coords(om-4))
print("compare: [1-om]", coords(1-om), "  [-3-om]", coords(-3-om),
      "   -- the same two, times [-1] =", coords(KK(-1)))
print()
# delta is a homomorphism:  delta(T) * delta(P) = delta(T+P) = delta(Q)
print("(om-1)(3+om)             =", (om-1)*(3+om), "   coords", coords((om-1)*(3+om)))
print("same class as 1/4 - 3om ?", is_sq((om-1)*(3+om)*(QQ(1)/4-3*om)))
print()
print("[-1] in the image ?      ",
      coords(KK(-1)) in [coords(z) for z in [KK(1), om-1, 3+om, om-4]])

[3-3om]    == [om-1] ? True    (3 is not a square, but -3 is)
[-9-3om]   == [3+om] ? True    since -9-3om = -3*(3+om) and -3 is a square
[1/4-3om]  == [om-4] ? True

coords:  [om-1] (0, 1, 1, 0)   [3+om] (0, 1, 0, 1)   [om-4] (0, 0, 1, 1)
compare: [1-om] (0, 0, 1, 0)   [-3-om] (0, 0, 0, 1)    -- the same two, times [-1] = (0, 1, 0, 0)

(om-1)(3+om)             = om - 4    coords (0, 0, 1, 1)
same class as 1/4 - 3om ? True

[-1] in the image ?       False


## 7. An independent brute-force scan

Forget the theory: sample $x \in \mathbb{Q}$ (dense in $\mathbb{Q}_2$) with $x^3-3$ a square in
$\mathbb{Q}_2$ — every such $x$ gives a genuine point of $E(\mathbb{Q}_2)$ — and record the class of
$x - 3\omega$. Exactly four classes should appear, the four above. As in the $x^3+3$ notebook, $T$
itself is never found this way: its $x$-coordinate is irrational.

In [11]:
seen, count, byk = {}, 0, {}

for k in range(7):                            # x of valuation 0, -2, -4, ..., -12
    for a in range(-400, 401):
        if k > 0 and a % 2 == 0:
            continue
        x = QQ(a) / 4^k
        if not Q2(x^3 - 3).is_square():
            continue
        count += 1
        c = coords(KK(x) - 3*om)
        seen.setdefault(c, x)
        byk.setdefault(-2*k, set()).add(c)

print("points sampled           :", count)
print("distinct classes reached :", len(seen))
for c in sorted(seen):
    print("   ", c, "  first seen at x =", seen[c])
print()
for v in sorted(byk, reverse=True):
    print("   v_2(x) =", str(v).rjust(3), " classes:", sorted(byk[v]))
print("=> integral x reaches only the classes of T and P; the class of Q needs v_2(x) = -2,")
print("   and the trivial class 2E = E_2 is reached only from v_2(x) <= -4.")

points sampled           : 632
distinct classes reached : 4
    (0, 0, 0, 0)   first seen at x = -399/16
    (0, 0, 1, 1)   first seen at x = -399/4
    (0, 1, 0, 1)   first seen at x = -393
    (0, 1, 1, 0)   first seen at x = -341

   v_2(x) =   0  classes: [(0, 1, 0, 1), (0, 1, 1, 0)]
   v_2(x) =  -2  classes: [(0, 0, 1, 1)]
   v_2(x) =  -4  classes: [(0, 0, 0, 0)]
   v_2(x) =  -6  classes: [(0, 0, 0, 0)]
   v_2(x) =  -8  classes: [(0, 0, 0, 0)]
   v_2(x) = -10  classes: [(0, 0, 0, 0)]
   v_2(x) = -12  classes: [(0, 0, 0, 0)]
=> integral x reaches only the classes of T and P; the class of Q needs v_2(x) = -2,
   and the trivial class 2E = E_2 is reached only from v_2(x) <= -4.


## 8. Where the image sits: duality, and the Frobenius twist

$\#H^1(\mathbb{Q}_2, E[2]) = 16$, so local Tate duality forces the image to be **maximal isotropic**
of order $4$. The pairing that does this is *not* the Hilbert symbol of $\mathbb{Q}_4$: the Weil
pairing on $E[2] = \operatorname{Ind}\mu_2$ is the standard pairing of the induced module *composed
with the swap* of the two conjugate points, so under Shapiro the Tate pairing becomes the Frobenius
twist $(a,b) \mapsto (a, \sigma b)_{\mathbb{Q}_4}$.

Hilbert symbols of $\mathbb{Q}_4$ are computed in $\mathbb{Q}(\omega)$ at its prime above $2$, which
is inert — so that completion *is* $\mathbb{Q}_4$.

In [12]:
P2 = KK.primes_above(2)[0]
print("prime above 2 :", P2, "   e =", P2.ramification_index(), "  f =", P2.residue_class_degree())

def hs(u, v):
    "Hilbert symbol of Q_4"
    return KK.hilbert_symbol(u, v, P2)

def sig(z):
    "the Frobenius of Q_4/Q_2:  om |-> om^2"
    a, b = z.list()
    return a + b*om^2

im = [KK(1), om - 1, om - 4, 3 + om]
print("sigma(om-1) =", sig(om-1), "    sigma(3+om) =", sig(3+om))
print()
print("plain    ((u_i, u_j))       ="); show(matrix(4, 4, lambda i, j: hs(im[i], im[j])))
print("twisted  ((u_i, sigma u_j)) ="); show(matrix(4, 4, lambda i, j: hs(im[i], sig(im[j]))))

prime above 2 : Fractional ideal (2)    e = 1   f = 2
sigma(om-1) = -om - 2     sigma(3+om) = -om + 2

plain    ((u_i, u_j))       =


[ 1  1  1  1]
[ 1 -1  1 -1]
[ 1  1  1  1]
[ 1 -1  1 -1]

twisted  ((u_i, sigma u_j)) =


[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]

In [13]:
ann = [rep(m) for m in range(16)
       if hs(rep(m), sig(om - 1)) == 1 and hs(rep(m), sig(3 + om)) == 1]

print("twisted annihilator :", len(ann), "classes:", ann)
print("equals the image ?  ", sorted(coords(z) for z in ann) == sorted(coords(u) for u in im))
print()
print("(z, sigma z) = 1 for all 16 classes ?",
      all(hs(rep(m), sig(rep(m))) == 1 for m in range(16)), " => the form is alternating")
print("number of maximal isotropic (Lagrangian) subgroups of order 4 :",
      len(set(frozenset([0, m, n, m ^^ n]) for m in range(1,16) for n in range(1,16)
              if m != n and hs(rep(m), sig(rep(n))) == 1)))
print()
print("all four classes are unit classes (even though the reduction at 2 is additive):",
      all(to2(u).valuation() % 2 == 0 for u in im))
print("(-1, sigma(om-1)) =", hs(-1, sig(om-1)),
      "  so [-1] is NOT in the image, and Im(delta) = { z in H_ur : (z, sigma(om-1)) = 1 }")

twisted annihilator : 4 classes: [1, om - 1, om + 3, om - 4]
equals the image ?   True

(z, sigma z) = 1 for all 16 classes ? True  => the form is alternating
number of maximal isotropic (Lagrangian) subgroups of order 4 : 15

all four classes are unit classes (even though the reduction at 2 is additive): True
(-1, sigma(om-1)) = -1   so [-1] is NOT in the image, and Im(delta) = { z in H_ur : (z, sigma(om-1)) = 1 }


The plain symbol is **not** trivial on the image, while the twisted one vanishes identically and its
annihilator is the image itself. So the image is one of the $15$ Lagrangians, maximal isotropic on
the nose, and the swap is not bookkeeping: it is what makes duality come out.

## 9. Closing the family: $b \in \{1,-1,3,-3\}$

Two facts organise the whole family $y^2 = x^3+b$ with $b \in \mathbb{Z}_2^\times$.

1. **There are exactly four curves over $\mathbb{Q}_2$.** $y^2=x^3+b \cong y^2=x^3+b'$ over $K$ iff
   $b/b' \in (K^\times)^6$; on $2$-adic units sixth powers are just squares (cubing is onto), so the
   invariant is $b \bmod 8$. The four notebooks use $b = 1, -1, 3, -3$, of classes $1, 7, 3, 5$ —
   all of them.
2. **The identification of $2$-torsion is $\mathbb{Q}_2$-rational.** The roots of $x^3+b$ are
   $\lambda$ times those of $x^3+b'$ with $\lambda = (b/b')^{1/3} \in \mathbb{Z}_2^\times$, so
   $(x,0)\mapsto(\lambda x,0)$ identifies $E_{b'}[2] \cong E_b[2]$ over $\mathbb{Q}_2$ and matches the
   *normalised* distinguished roots $\rho_b := (-b)^{1/3}\,\omega$ for all odd $b$ at once. This
   notebook uses $\rho_{-3} = \sqrt[3]{3}\,\omega = \varphi\omega$; the $b=1$ notebook used
   $\zeta_6 = -\omega^2$, whose normalised partner is $\rho_1 = (-1)^{1/3}\omega = -\omega$, i.e. its
   Frobenius conjugate.

Quadratic twisting by $5$ — the class cutting out $\mathbb{Q}_4$ — sends $b \mapsto 5^3 b \equiv 5b$
mod $8$, so it pairs $\{1, -3\}$ and $\{-1, 3\}$. Each pair shares its Kodaira type (the twist is
unramified) and, as it turns out, its Kummer image; the Tamagawa number need not survive.

In [14]:
print(" b   label   b mod 8   Kodaira  c_2   E(Q)                 Im(delta) in the basis B")
rows = {}
for b in [1, -1, 3, -3]:
    Eb = EllipticCurve([0,0,0,0,b]); ldb = Eb.local_data(2)
    rows[b] = (Eb.cremona_label(), b % 8, str(ldb.kodaira_symbol()), ldb.tamagawa_number(),
               ("rank " + str(Eb.rank()) + ", tors " + str(Eb.torsion_subgroup().invariants())))

# images, each written with its NORMALISED root rho_b = (-b)^(1/3) * om
imag = {-3: [KK(1), om - 1, om - 4, 3 + om],                          # this notebook
         3: [KK(1), 1 - om, om - 4, -3 - om],                          # b = 3   notebook
        -1: [KK(1), 1 - om, om - 4, -3 - om],                          # b = -1  notebook
         1: [sig(z) for z in [KK(1), -2 - om, -5 - om, -3 - om]]}      # b = 1, zeta_6 -> -om
for b in [1, -1, 3, -3]:
    lab, b8, kod, c2, mw = rows[b]
    print(str(b).rjust(2), lab.rjust(7), str(b8).rjust(6), "  ", kod.ljust(4), str(c2).rjust(3),
          "  " + mw.ljust(20), sorted(coords(z) for z in imag[b]))
print()
A = sorted(coords(z) for z in imag[-1])
print("Im(-1) == Im(3)   ?", A == sorted(coords(z) for z in imag[3]))
print("Im(1)  == Im(-3)  ?", sorted(coords(z) for z in imag[1]) == sorted(coords(z) for z in imag[-3]))
print("the two are Frobenius conjugate:",
      sorted(coords(sig(z)) for z in imag[-1]) == sorted(coords(z) for z in imag[-3]))
print("and distinct           :", A != sorted(coords(z) for z in imag[-3]))
print()
print("unramified twist check:  -3/125 =", QQ(-3)/125, " a square in Q_2 ?", Q2(QQ(-3)/125).is_square())
print("   => y^2 = x^3-3  ~  y^2 = x^3+125 over Q_2, and y^2 = x^3+125 =",
      EllipticCurve([0,0,0,0,1]).quadratic_twist(5).short_weierstrass_model().ainvs())

 b   label   b mod 8   Kodaira  c_2   E(Q)                 Im(delta) in the basis B
 1    36a1      1    IV     3   rank 0, tors (6,)    [(0, 0, 0, 0), (0, 0, 1, 1), (0, 1, 0, 1), (0, 1, 1, 0)]
-1   144a1      7    II     1   rank 0, tors (2,)    [(0, 0, 0, 0), (0, 0, 0, 1), (0, 0, 1, 0), (0, 0, 1, 1)]
 3  3888t1      3    II     1   rank 1, tors ()      [(0, 0, 0, 0), (0, 0, 0, 1), (0, 0, 1, 0), (0, 0, 1, 1)]
-3   972b1      5    IV     1   rank 0, tors ()      [(0, 0, 0, 0), (0, 0, 1, 1), (0, 1, 0, 1), (0, 1, 1, 0)]

Im(-1) == Im(3)   ? True
Im(1)  == Im(-3)  ? True
the two are Frobenius conjugate: True
and distinct           : True

unramified twist check:  -3/125 = -3/125  a square in Q_2 ? True
   => y^2 = x^3-3  ~  y^2 = x^3+125 over Q_2, and y^2 = x^3+125 = (0, 0, 0, 0, 125)


So the four unit curves realise exactly **two** maximal isotropic subgroups of
$\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$, exchanged by Frobenius, and the pairing is by
unramified quadratic twist:
$$\{b \equiv 7, 3\} = \{-1, 3\} \ \longrightarrow\ \big\langle[1-\omega],[-3-\omega]\big\rangle,
\qquad
\{b \equiv 1, 5\} = \{1, -3\} \ \longrightarrow\ \big\langle[\omega-1],[3+\omega]\big\rangle .$$
Two curves of the same pair can still differ a lot elsewhere — $b=1$ has $c_2 = 3$ and
$E(\mathbb{Q}) \cong \mathbb{Z}/6$ while $b=-3$ has $c_2 = 1$ and $E(\mathbb{Q}) = 0$ — but their
local conditions at $2$ agree.

## Summary

$$V = \Big\{\mathcal{O},\ \big(\sqrt[3]{3},0\big),\ \big(-9,2\sqrt{-183}\big),\
\big(\tfrac14,\tfrac18\sqrt{-191}\big)\Big\},
\qquad \operatorname{Im}(\delta) = \big\langle [\omega-1],\ [3+\omega]\big\rangle .$$

- $E(\mathbb{Q}) = \{\mathcal{O}\}$ — rank $0$, no torsion — so **no** non-trivial coset contains a
  rational point; $T$ has irrational $x$ and $P, Q$ irrational $y$;
- $E[2](\mathbb{Q}) = 0$ but $E[2](\mathbb{Q}_2) \neq 0$: every $2$-adic unit is a cube, so
  $\varphi = \sqrt[3]{3} \in \mathbb{Z}_2$ and $T = (\varphi,0)$;
- $v_2(\varphi-3) = 3$ exactly — just enough for $x-\varphi\omega \rightsquigarrow x-3\omega$ modulo
  squares, keeping all bookkeeping in $\mathbb{Q}(\omega)$;
- the norm map carries the image isomorphically onto $\mathbb{Z}_2^\times/(\mathbb{Z}_2^\times)^2$,
  and the four norm classes $1,5,3,7 \bmod 8$ match the four layers
  $E_2,\ E_1\smallsetminus E_2,\ T+E_2,\ T+(E_1\smallsetminus E_2)$;
- the reduction is type $\mathrm{IV}$ with $c_2 = 1$, $E(\mathbb{Q}_2) = E_1 \oplus \langle T\rangle$
  is pro-$2$, and the coset of $Q$ reaches into the formal group;
- the image consists of **unit** classes and is maximal isotropic for the Frobenius-twisted Hilbert
  symbol, as local duality demands;
- it is the Frobenius conjugate of the subgroup attached to $b = -1, 3$: over $\mathbb{Q}_2$ this
  curve is the unramified quadratic twist of $y^2 = x^3+1$, and $[3] = [-1] \neq [1]$ in
  $\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$ is what tips it over.