# The local Kummer image at $p = 2$ for $y^2 = x^3 + 3$

For $E : y^2 = x^3+3$ (curve `3888t1`, $j = 0$, CM by $\mathbb{Z}[\zeta_3]$, conductor
$3888 = 2^4\cdot 3^5$, **rank $1$** with generator $P = (1,2)$ and trivial torsion) we write down an
explicit finite set $V \subset E(\mathbb{Q}_2)$ representing $E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$ and
compute its image under the local Kummer map at $2$ inside
$$\mathbb{Q}_4 \;=\; \mathbb{Q}_2(\omega) \;=\; \mathbb{Q}_2(\sqrt{-3}) \;=\; \mathbb{Q}_2(\sqrt 5),$$
the unramified quadratic extension of $\mathbb{Q}_2$.

**What is new here.** $x^3+3$ is *irreducible over $\mathbb{Q}$*, so $E[2](\mathbb{Q}) = 0$ — yet
$-3$ **is** a cube in $\mathbb{Z}_2$ (cubing is a bijection on the pro-$2$ group $\mathbb{Z}_2^\times$),
so over $\mathbb{Q}_2$ the curve acquires a $2$-torsion point
$$T = (e, 0), \qquad e = \sqrt[3]{-3} \in \mathbb{Z}_2^\times, \qquad e \equiv 5 \ (128),$$
whose $x$-coordinate is $2$-adic but irrational. The remaining factor $x^2+ex+e^2$ has discriminant
$-3e^2$, so once again $\mathbb{Q}_2(E[2]) = \mathbb{Q}_4$ and $E[2] = \operatorname{Ind}_{\mathbb{Q}_4}^{\mathbb{Q}_2}\mu_2$:
Shapiro gives $H^1(\mathbb{Q}_2,E[2]) \cong \mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$, of order $16$,
and the descent map is
$$\delta(x,y) = x - \rho, \qquad \rho = e\omega, \qquad
N_{\mathbb{Q}_4/\mathbb{Q}_2}\big(\delta(x,y)\big) = x^2+ex+e^2 .$$
The irrational $e$ would wreck exact bookkeeping — except that $e \equiv 5 \pmod{128}$ and square
classes only see three binary digits, so $\delta$ may be replaced by $x - 5\omega$ **on the nose**
(§3). Everything symbolic then happens in $\mathbb{Q}(\omega)$, as in the companion notebooks.

**The answer.**
$$V = \{\mathcal{O},\ T,\ P,\ Q\}
 = \Big\{\mathcal{O},\ \big(\sqrt[3]{-3},\,0\big),\ (1,2),\ \big(\tfrac14,\ \tfrac18\sqrt{193}\big)\Big\},$$
$$\operatorname{Im}(\delta) = \{1,\ 5-5\omega,\ 1-5\omega,\ \tfrac14-5\omega\}\cdot(\mathbb{Q}_4^\times)^2
 = \big\langle [1-\omega],\, [-3-\omega] \big\rangle \subset \mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2 .$$
The four classes are distinct for the usual one-line reason: their norms are $1,\ 75,\ 31,\ 421/16$,
i.e. $1, 3, 7, 5$ mod $8$ — *all four* square classes of $\mathbb{Z}_2^\times$ — and a square has a
square norm.

That subgroup is **exactly** the one found for $y^2 = x^3-1$, and §9 explains why: over $\mathbb{Q}_2$
this curve is the *unramified* quadratic twist of that one, and the two $2$-torsion modules are
canonically identified by a $\mathbb{Q}_2$-rational scaling.

Companions: `local-kummer-p2.ipynb` ($y^2 = x^3+1$) and `local-kummer-p2-minus.ipynb` ($y^2 = x^3-1$).

## 1. The curve at $2$, and the size of $E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$

In [1]:
E = EllipticCurve([0,0,0,0,3])              # y^2 = x^3 + 3
print("E             :", E)
print("discriminant  :", E.discriminant(), "=", factor(E.discriminant()))
print("j-invariant   :", E.j_invariant(), "   conductor:", factor(E.conductor()),
      "   label:", E.cremona_label())
print("globally minimal:", E.is_minimal())

ld = E.local_data(2)
print("at p = 2      : Kodaira", ld.kodaira_symbol(),
      "  f =", ld.conductor_valuation(), "  c_2 =", ld.tamagawa_number())
print("E(Q)          : torsion", E.torsion_subgroup().invariants(),
      "  rank", E.rank(), "  generator", [G.xy() for G in E.gens()])

E             : Elliptic Curve defined by y^2 = x^3 + 3 over Rational Field
discriminant  : -3888 = -1 * 2^4 * 3^5
j-invariant   : 0    conductor: 2^4 * 3^5    label: 3888t1
globally minimal: True
at p = 2      : Kodaira II   f = 4   c_2 = 1
E(Q)          : torsion ()   rank 1   generator [(1, 2)]


### $E[2]$ is invisible over $\mathbb{Q}$ but half-visible over $\mathbb{Q}_2$

$\mathbb{Z}_2^\times \cong \mu_2 \times \mathbb{Z}_2$ is a pro-$2$ group, and $3$ is invertible in
$\mathbb{Z}_2$, so **cubing is an automorphism of $\mathbb{Z}_2^\times$**: every $2$-adic unit is a
cube. Hence $x^3+3$ has the root $e = \sqrt[3]{-3} \in \mathbb{Z}_2^\times$ even though it is
irreducible over $\mathbb{Q}$.

In [2]:
R.<X> = QQ[]
print("x^3 + 3 over Q   :", factor(X^3 + 3), "   irreducible => E[2](Q) = 0")
print("cubing on (Z/8)^*:", {u: (u^3) % 8 for u in [1,3,5,7]}, "  -- a bijection")
print()
Z2 = Zp(2, 60)
e  = Z2(-3).nth_root(3)
print("e = (-3)^(1/3)   :", e)
print("e^3 + 3          :", e^3 + 3)
print("e mod 8, 128, 256:", e.lift() % 8, ",", e.lift() % 128, ",", e.lift() % 256,
      "     v_2(e - 5) =", (e - 5).valuation())
print()
S.<Y> = Z2[]
print("(Y-e)(Y^2+eY+e^2) - (Y^3+3) =", (Y - e)*(Y^2 + e*Y + e^2) - (Y^3 + 3), "  -- exact split over Q_2")
print("disc(x^2+ex+e^2) = e^2 - 4e^2 = -3e^2")
print("-3 a square in Q_2 ?", Qp(2,20)(-3).is_square(),
      "  => the quadratic factor generates Q_4 = Q_2(sqrt(-3))")
print("=> E(Q_2)[2] = {O, T},  T = (e,0),  r_2 = 1")
print("=> #E(Q_2)/2E(Q_2) = #E(Q_2)[2] * |2|_2^(-1) = 2 * 2 = 4")

x^3 + 3 over Q   : X^3 + 3    irreducible => E[2](Q) = 0
cubing on (Z/8)^*: {1: 1, 3: 3, 5: 5, 7: 7}   -- a bijection

e = (-3)^(1/3)   : 1 + 2^2 + 2^7 + 2^9 + 2^10 + 2^11 + 2^17 + 2^18 + 2^19 + 2^20 + 2^22 + 2^23 + 2^28 + 2^29 + 2^33 + 2^36 + 2^37 + 2^39 + 2^41 + 2^44 + 2^45 + 2^57 + 2^58 + 2^59 + O(2^60)
e^3 + 3          : O(2^60)
e mod 8, 128, 256: 5 , 5 , 133      v_2(e - 5) = 7

(Y-e)(Y^2+eY+e^2) - (Y^3+3) = O(2^60)*Y^3 + O(2^60)*Y^2 + O(2^60)*Y + O(2^60)   -- exact split over Q_2
disc(x^2+ex+e^2) = e^2 - 4e^2 = -3e^2
-3 a square in Q_2 ? False   => the quadratic factor generates Q_4 = Q_2(sqrt(-3))
=> E(Q_2)[2] = {O, T},  T = (e,0),  r_2 = 1
=> #E(Q_2)/2E(Q_2) = #E(Q_2)[2] * |2|_2^(-1) = 2 * 2 = 4


Type $\mathrm{II}$ with $c_2 = 1$ pins the group down exactly as for $y^2 = x^3-1$:
$E(\mathbb{Q}_2) = E_0$, $E_0/E_1 \cong \tilde E_{\mathrm{ns}}(\mathbb{F}_2) = (\mathbb{F}_2,+)$ and
$E_1 \cong \mathbb{Z}_2$, so $E(\mathbb{Q}_2)$ is **pro-$2$**. The reduction $\tilde E : y^2 = x^3+1$
over $\mathbb{F}_2$ has its singular point at $(0,1)$; since $e$ is a unit, $T = (e,0)$ reduces to the
*smooth* point $(1,0)$, so $T \notin E_1$ and, having order $2$ and generating $E_0/E_1$, it splits
the filtration:
$$E(\mathbb{Q}_2) \;=\; E_1 \oplus \langle T\rangle \;\cong\; \mathbb{Z}_2 \oplus \mathbb{Z}/2,
\qquad 2E(\mathbb{Q}_2) = 2E_1 = E_2 ,$$
so the four cosets are $E_2$, $E_1\smallsetminus E_2$, $T+E_2$, $T+(E_1\smallsetminus E_2)$.

**The global points are again not enough**, and now for a doubly awkward reason: $E(\mathbb{Q})$ is
free of rank $1$ with no torsion, so $E(\mathbb{Q})/2E(\mathbb{Q}) = \{0,[P]\} \cong \mathbb{Z}/2$
reaches only two of the four cosets — and the missing $2$-torsion point $T$ is not global either.

## 2. The field $\mathbb{Q}_4$, and which classes are squares

In [3]:
K2.<w> = Qq(4, 40)                 # unramified quadratic extension of Q_2; w = zeta_3
print("K2            :", K2)
print("residue field :", K2.residue_field(), "   e =", K2.e(), "  f =", K2.f())
print("w^2 + w + 1   =", w^2 + w + 1)
print("(1 + 2w)^2    =", (1 + 2*w)^2 + O(2^10), "  ...   so sqrt(-3) = 1 + 2w")
print()
for c in [-1, 2, 5, -3, 3, 7, 21, 31, 75]:
    print("  [" + str(c).rjust(3) + "] a square in Q_4 ?  " + str(K2(c).is_square()))

K2            : 2-adic Unramified Extension Field in w defined by x^2 + x + 1
residue field : Finite Field in w0 of size 2^2    e = 1   f = 2
w^2 + w + 1   = O(2^40)
(1 + 2w)^2    = 1 + 2^2 + 2^3 + 2^4 + 2^5 + 2^6 + 2^7 + 2^8 + 2^9 + O(2^10)   ...   so sqrt(-3) = 1 + 2w

  [ -1] a square in Q_4 ?  False
  [  2] a square in Q_4 ?  False
  [  5] a square in Q_4 ?  True
  [ -3] a square in Q_4 ?  True
  [  3] a square in Q_4 ?  False
  [  7] a square in Q_4 ?  False
  [ 21] a square in Q_4 ?  True
  [ 31] a square in Q_4 ?  False
  [ 75] a square in Q_4 ?  False


A unit of $\mathbb{Q}_4$ is a square as soon as it is one **mod $8$**: $(1+4a)^2 = 1+8(a+2a^2)$ and
$a \mapsto a+2a^2$ is bijective on $\mathcal{O}$ by Hensel, so $1+8\mathcal{O} \subset
(\mathcal{O}^\times)^2$. That single fact is used twice below — once to count
$\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$, and once (in §3) to replace the irrational $e$ by $5$.

For $a \in \mathbb{Q}_2^\times$: $a$ is a square in $\mathbb{Q}_4$ exactly when $v_2(a)$ is even and
its unit part is $\equiv 1$ or $5 \pmod 8$. In particular $[3] = [7] = [31] = [75] = [-1]$ and
$[21] = [1]$, even though $3, 7, 21, 31$ are non-squares in $\mathbb{Q}_2$.

### Why $\#\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2 = 2^{[\mathbb{Q}_4:\mathbb{Q}_2]+2} = 16$

For any finite $K/\mathbb{Q}_2$ of degree $d$ with residue field of size $q$,
$$K^\times \cong \pi^{\mathbb{Z}} \times \mu_{q-1} \times U^{(1)}, \qquad
U^{(1)} \cong \mu_{2^\infty}(K) \times \mathbb{Z}_2^{\,d},$$
the second isomorphism because $\log$ carries $U^{(m)}$ onto $\mathfrak{m}^m \cong (\mathcal{O},+)$
for $m > e/(p-1)$. Modulo squares: $\pi^{\mathbb{Z}}$ gives $2$; $\mu_{q-1}$ has **odd** order and
gives nothing; $\mathbb{Z}_2^d$ gives $2^d$; $\mu_{2^\infty}(K) \ni -1$ gives $2$. Total $2^{d+2}$.

For $\mathbb{Q}_4$: $d = 2$, $q = 4$, odd part $\mu_3$, and $\mu_{2^\infty}(\mathbb{Q}_4) = \{\pm1\}$
since $\mathbb{Q}_2(i)$ is *ramified*. So the order is $16$, and a basis should consist of one class
of odd valuation, $[-1]$, and two unit classes. The finite check, in a ring of $64$ elements:

In [4]:
def mul8(u, v):
    "product in O/8O = (Z/8)[w]/(w^2+w+1), elements written as pairs (a,b) = a + b*w"
    (a, b), (c, d) = u, v
    return ((a*c - b*d) % 8, (a*d + b*c - b*d) % 8)

units8   = [(a, b) for a in range(8) for b in range(8) if (a^2 - a*b + b^2) % 2 == 1]
squares8 = sorted(set(mul8(u, u) for u in units8))

print("#(O/8O)^*  =", len(units8), "   squares:", len(squares8), squares8, " = mu_3 * {1, 5}")
print("index      =", len(units8) // len(squares8), " = #O^*/(O^*)^2")
print("times the Z/2 from the valuation:  #Q_4^*/(Q_4^*)^2 =",
      2 * len(units8) // len(squares8))

#(O/8O)^*  = 48    squares: 6 [(0, 1), (0, 5), (1, 0), (3, 3), (5, 0), (7, 7)]  = mu_3 * {1, 5}
index      = 8  = #O^*/(O^*)^2
times the Z/2 from the valuation:  #Q_4^*/(Q_4^*)^2 = 16


## 3. Getting rid of $e$: the substitution $\delta(x,y) = x - e\omega \;\rightsquigarrow\; x - 5\omega$

Write elements of $\mathbb{Q}_4$ as $\alpha + \beta\omega$ with $\alpha,\beta \in \mathbb{Q}_2$;
since $\{1,\omega\}$ is an integral basis, $v(\alpha+\beta\omega) = \min(v\alpha, v\beta)$.

> **Lemma.** Let $z = \alpha+\beta\omega \neq 0$ and $\tilde z = \tilde\alpha + \tilde\beta\omega$ with
> $\min\big(v(\alpha-\tilde\alpha),\, v(\beta-\tilde\beta)\big) \geq v(z) + 3$. Then
> $\tilde z / z \in 1 + 8\mathcal{O}$, hence $[\tilde z] = [z]$ in $\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$.
>
> *Proof.* $\tilde z/z = 1 + (\tilde z - z)/z$ and $v\big((\tilde z-z)/z\big) \geq 3$; now
> $1+8\mathcal{O}$ consists of squares (§2). $\square$

Apply it to $z = \delta(x,y) = x - e\omega$ with $x \in \mathbb{Q}_2$. Here
$v(z) = \min(v(x), 0) \leq 0$, so the hypothesis is implied by $v(x - \tilde x) \geq 3$ and
$v(e - 5) \geq 3$ — and in fact $v(e-5) = 7$. Therefore, **for every $x \in \mathbb{Q}_2$ and every
rational $\tilde x \equiv x \pmod 8$,**
$$[\,x - e\omega\,] = [\,\tilde x - 5\omega\,] \quad\text{in } \mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2 .$$
In particular the $2$-torsion point $T = (e,0)$ has $\delta(T) = e(1-\omega)$ of class
$[5 - 5\omega] = [1-\omega]$, since $5$ is a square in $\mathbb{Q}_4$. So nothing irrational survives
into the answer, and all symbolic work below can be done in the exact field $\mathbb{Q}(\omega)$.

In [5]:
eK = K2(e)
print("checking [x - e*w] == [x - 5*w] for x = a/4^k, a in [-60,60], k = 0,1,2 :")
bad = [(QQ(a)/4^k) for k in range(3) for a in range(-60, 61)
       if K2(QQ(a)/4^k) - eK*w != 0
       and not ((K2(QQ(a)/4^k) - eK*w) * (K2(QQ(a)/4^k) - 5*w)).is_square()]
print("   failures:", bad)
print()
print("and at the 2-torsion point itself, x = e:")
print("   [e - e*w] == [5 - 5*w] ?", ((eK - eK*w) * (K2(5) - 5*w)).is_square())
print("   [5 - 5*w] == [1 - w]   ?", ((K2(5) - 5*w) * (K2(1) - w)).is_square(),
      "   (because 5 is a square in Q_4)")

checking [x - e*w] == [x - 5*w] for x = a/4^k, a in [-60,60], k = 0,1,2 :
   failures: []

and at the 2-torsion point itself, x = e:
   [e - e*w] == [5 - 5*w] ? True
   [5 - 5*w] == [1 - w]   ? True    (because 5 is a square in Q_4)


## 4. A basis of $\mathbb{Q}_4^\times/(\mathbb{Q}_4^\times)^2$, and coordinates

The same basis as in the $x^3-1$ notebook, $B = (2,\ -1,\ 1-\omega,\ -3-\omega)$, so that the two
images can be compared literally in §9.

In [6]:
KK.<om> = CyclotomicField(3)         # exact home for everything symbolic; om = zeta_3

def to2(z):
    "image of z in Q_4 under om |-> w"
    a, b = z.list()
    return K2(a) + K2(b)*w

def nrm(z):
    "exact norm to Q of a + b*om"
    a, b = z.list()
    return a^2 - a*b + b^2

def is_sq(z):
    "is z a square in Q_4 ?"
    return to2(z).is_square()

def cls(q):
    "the square class of q in Q_2^*, as (v_2(q) mod 2, unit part mod 8)"
    q = QQ(q); v = q.valuation(2); u = q / 2^v
    return (v % 2, ZZ(u.numerator() * ZZ(u.denominator()).inverse_mod(8)) % 8)

B      = [KK(2), KK(-1), 1 - om, -3 - om]
Bnames = ["2", "-1", "1-om", "-3-om"]

def rep(m):
    "the product of the basis elements selected by the bits of m"
    z = KK(1)
    for i in range(4):
        if (m >> i) & 1:
            z *= B[i]
    return z

def coords(z):
    "coordinates of the class of z in the basis B, found by testing squareness"
    for m in range(16):
        if is_sq(z * rep(m)):
            return tuple((m >> i) & 1 for i in range(4))
    raise ValueError("z is not in the span of B")

print("basis:", Bnames)
print()
print("  coords          representative     norm    square?")
for m in range(16):
    z = rep(m)
    c = tuple((m >> i) & 1 for i in range(4))
    print("  " + str(c) + "   " + str(z).rjust(17) + "   "
          + str(nrm(z)).rjust(5) + "    " + str(is_sq(z)))

basis: ['2', '-1', '1-om', '-3-om']

  coords          representative     norm    square?
  (0, 0, 0, 0)                   1       1    True
  (1, 0, 0, 0)                   2       4    False
  (0, 1, 0, 0)                  -1       1    False
  (1, 1, 0, 0)                  -2       4    False
  (0, 0, 1, 0)             -om + 1       3    False
  (1, 0, 1, 0)           -2*om + 2      12    False
  (0, 1, 1, 0)              om - 1       3    False
  (1, 1, 1, 0)            2*om - 2      12    False
  (0, 0, 0, 1)             -om - 3       7    False
  (1, 0, 0, 1)           -2*om - 6      28    False
  (0, 1, 0, 1)              om + 3       7    False
  (1, 1, 0, 1)            2*om + 6      28    False
  (0, 0, 1, 1)              om - 4      21    False
  (1, 0, 1, 1)            2*om - 8      84    False
  (0, 1, 1, 1)             -om + 4      21    False
  (1, 1, 1, 1)           -2*om + 8      84    False


Only the empty product is a square, so $B$ really is an $\mathbb{F}_2$-basis and `coords` is well
defined on classes.

## 5. The set $V$

Which $x$ occur? For $x \in \mathbb{Z}_2$ the norm $x^2+ex+e^2$ is a **unit** (mod $2$ it is
$x^2+x+1 \equiv 1$), so $v_2(x^3+3) = v_2(x-e)$. An even $x$ gives $x^3+3 \equiv 3 \pmod 8$, never a
square; so $x$ is odd and $v_2(x-e)$ must be even and positive, i.e. $x \equiv e \equiv 1 \pmod 4$.
Substituting $e \rightsquigarrow 5$, the norm class is then read off from $x$ mod $8$:
$$x \equiv 1 \ (8) \Rightarrow x^2+5x+25 \equiv 7 \ (8), \qquad
  x \equiv 5 \ (8) \Rightarrow x^2+5x+25 \equiv 3 \ (8) .$$
So an integral $x$ never gives the norm classes $1$ or $5$. For $v_2(x) = -2k < 0$ write
$x^2+ex+e^2 = x^2(1 + ex^{-1} + e^2x^{-2})$: the unit part is $\equiv 1+4 \equiv 5 \pmod 8$ when
$k = 1$ and $\equiv 1 \pmod 8$ when $k \geq 2$. Together with §1 this labels the four cosets:
$$E_2 \leftrightarrow 1, \qquad E_1\smallsetminus E_2 \leftrightarrow 5, \qquad
T + E_2 \leftrightarrow 3, \qquad T + (E_1\smallsetminus E_2) \leftrightarrow 7 \pmod 8 .$$

In [7]:
Q2 = Qp(2, 60)

print("sampled x = a/4^k with x^3+3 a square in Q_2, sorted by v_2(x):")
print("   v_2(x)   #sampled   classes of N = x^2+5x+25   as (v mod 2, unit mod 8)")
for k in range(4):
    found = [QQ(a)/4^k for a in range(-300, 301)
             if (k == 0 or a % 2) and Q2(QQ(a)^3/4^(3*k) + 3).is_square()]
    print("   " + str(-2*k).rjust(6) + str(len(found)).rjust(11) + "         "
          + str(sorted(set(cls(x^2 + 5*x + 25) for x in found))))
print()
print("integral x, by residue mod 8:")
for c in [1, 5]:
    print("   x =", c, "mod 8   =>   x^2+5x+25 =", (c^2 + 5*c + 25) % 8, "mod 8")

sampled x = a/4^k with x^3+3 a square in Q_2, sorted by v_2(x):
   v_2(x)   #sampled   classes of N = x^2+5x+25   as (v mod 2, unit mod 8)
        0         24         [(0, 3), (0, 7)]
       -2         75         [(0, 5)]
       -4         75         [(0, 1)]
       -6         75         [(0, 1)]

integral x, by residue mod 8:
   x = 1 mod 8   =>   x^2+5x+25 = 7 mod 8
   x = 5 mod 8   =>   x^2+5x+25 = 3 mod 8


So the three non-trivial cosets are reached by

$$T = (e,0) \ \ [x \equiv 5\ (8)], \qquad P = (1,2) \ \ [x \equiv 1\ (8)], \qquad
Q = \Big(\tfrac14,\ \tfrac18\sqrt{193}\Big) \ \ [v_2(x) = -2],$$

with $\big(\tfrac14\big)^3+3 = \tfrac{193}{64}$ and $193 \equiv 1 \pmod 8$, so $\sqrt{193} \in \mathbb{Z}_2^\times$
and $Q \in E_1(\mathbb{Q}_2)$ is a generator of $E_1 \cong \mathbb{Z}_2$. Note that $P$ is the global
generator, while $T$ has irrational $x$ and $Q$ irrational $y$.

That $Q$ represents the coset of $T+P$ is checked **exactly**, in the cubic field
$\mathbb{Q}(\sqrt[3]{-3})$ where $T$ becomes rational:

In [8]:
print("193 mod 8 =", 193 % 8, "   sqrt(193) in Q_2 ?", Q2(193).is_square(),
      "   (1/4)^3 + 3 =", QQ(1)/4^3 + 3)
print()
L.<rho> = NumberField(X^3 + 3)               # rho = cube root of -3, rho |-> e in Q_2
EL = EllipticCurve(L, [0,0,0,0,3])
TL, PL = EL([rho, 0]), EL([1, 2])
S = TL + PL
print("T =", TL, "   P =", PL)
print("T + P =", S)
print("on the curve ?", S[1]^2 == S[0]^3 + 3)

xS = sum(K2(S[0].list()[i]) * eK^i for i in range(3))     # image of x(T+P) in Q_4
print()
print("v_2(x(T+P)) =", xS.valuation(), "  => T+P lies in E_1, as its norm class 5 demands")
print("[x(T+P) - e*w] == [1/4 - 5*w] ?", ((xS - eK*w) * (K2(QQ(1)/4) - 5*w)).is_square())
print("=> Q = T + P  in E(Q_2)/2E(Q_2)")

193 mod 8 = 1    sqrt(193) in Q_2 ? True    (1/4)^3 + 3 = 193/64

T = (rho : 0 : 1)    P = (1 : 2 : 1)
T + P = (3/4*rho^2 - 5/4*rho - 9/4 : 15/8*rho^2 + 27/8*rho - 9/8 : 1)
on the curve ? True

v_2(x(T+P)) = -2   => T+P lies in E_1, as its norm class 5 demands
[x(T+P) - e*w] == [1/4 - 5*w] ? True
=> Q = T + P  in E(Q_2)/2E(Q_2)


## 6. The image

In [9]:
pts = [("O", None, None), ("T = (e,0)", "e", 5), ("P = (1,2)", "1", 1),
       ("Q = (1/4,sqrt(193)/8)", "1/4", QQ(1)/4)]

print("point".rjust(22) + " " + "x".rjust(4) + "   "
      + "delta ~ xt - 5om".rjust(17) + " " + "N".rjust(7) + " "
      + "class of N".rjust(11) + "   coords")
for name, xname, xt in pts:
    z = KK(1) if xt is None else KK(xt) - 5*om
    print(name.rjust(22) + " " + (xname or "-").rjust(4) + "   "
          + str(z).rjust(17) + " " + str(nrm(z)).rjust(7) + " "
          + str(cls(nrm(z))).rjust(11) + "   " + str(coords(z)))

                 point    x    delta ~ xt - 5om       N  class of N   coords
                     O    -                   1       1      (0, 1)   (0, 0, 0, 0)
             T = (e,0)    e           -5*om + 5      75      (0, 3)   (0, 0, 1, 0)
             P = (1,2)    1           -5*om + 1      31      (0, 7)   (0, 0, 0, 1)
 Q = (1/4,sqrt(193)/8)  1/4         -5*om + 1/4  421/16      (0, 5)   (0, 0, 1, 1)


**Theorem.** $V = \{\mathcal{O}, T, P, Q\}$ is a complete set of representatives for
$E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$, and
$$\operatorname{Im}(\delta) = \{1,\ 5-5\omega,\ 1-5\omega,\ \tfrac14-5\omega\}\cdot(\mathbb{Q}_4^\times)^2
= \big\langle [1-\omega],\ [-3-\omega]\big\rangle \cong (\mathbb{Z}/2)^2 .$$

*Proof.* A square in $\mathbb{Q}_4$ has square norm in $\mathbb{Q}_2$. The four norms are
$1,\ 75,\ 31,\ 421/16 \equiv 1, 3, 7, 5 \pmod 8$, four different classes of
$\mathbb{Q}_2^\times/(\mathbb{Q}_2^\times)^2$; so the four values of $\delta$ lie in four different
classes. As $\delta$ is injective on $E(\mathbb{Q}_2)/2E(\mathbb{Q}_2)$, of order $4$, the four
points represent all four cosets and their $\delta$-values are the whole image. $\blacksquare$

The pretty representatives are $[5-5\omega] = [1-\omega]$ (norm class $3$), $[1-5\omega] = [-3-\omega]$
(norm class $7$) and $[\tfrac14-5\omega] = [\omega-4]$ (norm class $5$):

In [10]:
print("[5-5om]   == [1-om]  ?", is_sq((5-5*om)*(1-om)),      "   (5 is a square in Q_4)")
print("[1-5om]   == [-3-om] ?", is_sq((1-5*om)*(-3-om)),     "   product =", (1-5*om)*(-3-om),
      ", norm", nrm((1-5*om)*(-3-om)), "= 1 mod 8")
print("[1/4-5om] == [om-4]  ?", is_sq((QQ(1)/4-5*om)*(om-4)))
print()
# delta is a homomorphism:  delta(T) * delta(P) = delta(T+P) = delta(Q)
print("(1-om)(-3-om)            =", (1-om)*(-3-om), "   coords", coords((1-om)*(-3-om)))
print("same class as 1/4 - 5om ?", is_sq((1-om)*(-3-om)*(QQ(1)/4-5*om)))
print()
print("[-1] in the image ?      ",
      coords(KK(-1)) in [coords(z) for z in [KK(1), 1-om, om-4, -3-om]])

[5-5om]   == [1-om]  ? True    (5 is a square in Q_4)
[1-5om]   == [-3-om] ? True    product = 9*om - 8 , norm 217 = 1 mod 8
[1/4-5om] == [om-4]  ? True

(1-om)(-3-om)            = om - 4    coords (0, 0, 1, 1)
same class as 1/4 - 5om ? True

[-1] in the image ?       False


## 7. An independent brute-force scan

Forget the theory: sample $x \in \mathbb{Q}$ (dense in $\mathbb{Q}_2$) with $x^3+3$ a square in
$\mathbb{Q}_2$ — every such $x$ gives a genuine point of $E(\mathbb{Q}_2)$ — and record the class of
$x - 5\omega$. Exactly four classes should appear, the four above. Note that $T$ itself is *not*
found this way: its $x$-coordinate is irrational.

In [11]:
seen, count, byk = {}, 0, {}

for k in range(7):                            # x of valuation 0, -2, -4, ..., -12
    for a in range(-400, 401):
        if k > 0 and a % 2 == 0:
            continue
        x = QQ(a) / 4^k
        if not Q2(x^3 + 3).is_square():
            continue
        count += 1
        c = coords(KK(x) - 5*om)
        seen.setdefault(c, x)
        byk.setdefault(-2*k, set()).add(c)

print("points sampled           :", count)
print("distinct classes reached :", len(seen))
for c in sorted(seen):
    print("   ", c, "  first seen at x =", seen[c])
print()
for v in sorted(byk, reverse=True):
    print("   v_2(x) =", str(v).rjust(3), " classes:", sorted(byk[v]))
print("=> integral x reaches only the classes of T and P; the class of Q needs v_2(x) = -2,")
print("   and the trivial class 2E = E_2 is reached only from v_2(x) <= -4.")

points sampled           : 634
distinct classes reached : 4
    (0, 0, 0, 0)   first seen at x = -399/16
    (0, 0, 0, 1)   first seen at x = -383
    (0, 0, 1, 0)   first seen at x = -331
    (0, 0, 1, 1)   first seen at x = -399/4

   v_2(x) =   0  classes: [(0, 0, 0, 1), (0, 0, 1, 0)]
   v_2(x) =  -2  classes: [(0, 0, 1, 1)]
   v_2(x) =  -4  classes: [(0, 0, 0, 0)]
   v_2(x) =  -6  classes: [(0, 0, 0, 0)]
   v_2(x) =  -8  classes: [(0, 0, 0, 0)]
   v_2(x) = -10  classes: [(0, 0, 0, 0)]
   v_2(x) = -12  classes: [(0, 0, 0, 0)]
=> integral x reaches only the classes of T and P; the class of Q needs v_2(x) = -2,
   and the trivial class 2E = E_2 is reached only from v_2(x) <= -4.


## 8. Where the image sits: duality, and the Frobenius twist

$\#H^1(\mathbb{Q}_2, E[2]) = 16$, so local Tate duality forces the image to be **maximal isotropic**
of order $4$. The pairing that does this is *not* the Hilbert symbol of $\mathbb{Q}_4$: the Weil
pairing on $E[2] = \operatorname{Ind}\mu_2$ is the standard pairing of the induced module *composed
with the swap* of the two conjugate points, so under Shapiro the Tate pairing becomes the Frobenius
twist $(a,b) \mapsto (a, \sigma b)_{\mathbb{Q}_4}$.

Hilbert symbols of $\mathbb{Q}_4$ are computed in $\mathbb{Q}(\omega)$ at its prime above $2$, which
is inert — so that completion *is* $\mathbb{Q}_4$.

In [12]:
P2 = KK.primes_above(2)[0]
print("prime above 2 :", P2, "   e =", P2.ramification_index(), "  f =", P2.residue_class_degree())

def hs(u, v):
    "Hilbert symbol of Q_4"
    return KK.hilbert_symbol(u, v, P2)

def sig(z):
    "the Frobenius of Q_4/Q_2:  om |-> om^2"
    a, b = z.list()
    return a + b*om^2

im = [KK(1), 1 - om, om - 4, -3 - om]
print("sigma(1-om) =", sig(1-om), "    sigma(-3-om) =", sig(-3-om))
print()
print("plain    ((u_i, u_j))       ="); show(matrix(4, 4, lambda i, j: hs(im[i], im[j])))
print("twisted  ((u_i, sigma u_j)) ="); show(matrix(4, 4, lambda i, j: hs(im[i], sig(im[j]))))

prime above 2 : Fractional ideal (2)    e = 1   f = 2
sigma(1-om) = om + 2     sigma(-3-om) = om - 2

plain    ((u_i, u_j))       =


[ 1  1  1  1]
[ 1 -1  1 -1]
[ 1  1  1  1]
[ 1 -1  1 -1]

twisted  ((u_i, sigma u_j)) =


[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]

In [13]:
ann = [rep(m) for m in range(16)
       if hs(rep(m), sig(1 - om)) == 1 and hs(rep(m), sig(-3 - om)) == 1]

print("twisted annihilator :", len(ann), "classes:", ann)
print("equals the image ?  ", sorted(coords(z) for z in ann) == sorted(coords(u) for u in im))
print()
print("(z, sigma z) = 1 for all 16 classes ?",
      all(hs(rep(m), sig(rep(m))) == 1 for m in range(16)), " => the form is alternating")
print("number of maximal isotropic (Lagrangian) subgroups of order 4 :",
      len(set(frozenset([0, m, n, m ^^ n]) for m in range(1,16) for n in range(1,16)
              if m != n and hs(rep(m), sig(rep(n))) == 1)))
print()
print("all four classes are unit classes (even though the reduction at 2 is additive):",
      all(to2(u).valuation() % 2 == 0 for u in im))
print("(-1, sigma(1-om)) =", hs(-1, sig(1-om)),
      "  so [-1] is NOT in the image, and Im(delta) = { z in H_ur : (z, sigma(1-om)) = 1 }")

twisted annihilator : 4 classes: [1, -om + 1, -om - 3, om - 4]
equals the image ?   True

(z, sigma z) = 1 for all 16 classes ? True  => the form is alternating
number of maximal isotropic (Lagrangian) subgroups of order 4 : 15

all four classes are unit classes (even though the reduction at 2 is additive): True
(-1, sigma(1-om)) = -1   so [-1] is NOT in the image, and Im(delta) = { z in H_ur : (z, sigma(1-om)) = 1 }


The plain symbol is **not** trivial on the image — already $(u,u)_{\mathbb{Q}_4} = -1$ for
$u = 1-\omega$ — while the twisted one vanishes identically and its annihilator is the image itself.
So the image is one of the $15$ Lagrangians, maximal isotropic on the nose, and the swap is not
bookkeeping: it is what makes duality come out.

## 9. Comparison: $y^2 = x^3+3$ is the *unramified* twist of $y^2 = x^3-1$

Two facts make the family $y^2 = x^3+b$, $b$ odd, easy to compare at $2$.

1. **The identification of $2$-torsion is $\mathbb{Q}_2$-rational.** The roots of $x^3+b$ are
   $\lambda$ times the roots of $x^3+b'$ with $\lambda = (b/b')^{1/3}$, and $\lambda \in \mathbb{Z}_2^\times$
   because every $2$-adic unit is a cube (§1). So $(x,0)\mapsto(\lambda x,0)$ identifies
   $E_{b'}[2] \cong E_b[2]$ over $\mathbb{Q}_2$, and it matches the *normalised* distinguished roots
   $\rho_b := (-b)^{1/3}\,\omega$ for all odd $b$ at once. This notebook uses $\rho_3 = e\omega$ and
   `local-kummer-p2-minus.ipynb` uses $\rho_{-1} = \omega$: they correspond, since
   $\lambda = (3/(-1))^{1/3} = e$.
2. **The curves are unramified quadratic twists.** $y^2 = x^3+b \cong y^2 = x^3+b'$ over $K$ iff
   $b/b' \in (K^\times)^6$; on units, sixth powers are just squares (cubing is onto), so over
   $\mathbb{Q}_2$ the invariant of $b$ is its class mod $8$. Here $3/(-125) = -3/125 \equiv 1 \pmod 8$,
   so $y^2 = x^3+3 \cong y^2 = x^3-125$ over $\mathbb{Q}_2$ — and $y^2=x^3-125$ is the quadratic twist
   of $y^2=x^3-1$ by $5$, the class cutting out $\mathbb{Q}_4$.

Hence the same Kodaira type, the same $c_2$, the same $E(\mathbb{Q}_2)$ — and, as it turns out, the
same image.

In [14]:
print("3/(-125) =", QQ(3)/(-125), "   class in Q_2^*/squares:", cls(QQ(3)/(-125)),
      "   a square in Q_2 ?", Q2(QQ(3)/(-125)).is_square())
print("   => y^2 = x^3+3  ~  y^2 = x^3-125 over Q_2, and")
print("      y^2 = x^3-125 =", EllipticCurve([0,0,0,0,-1]).quadratic_twist(5).short_weierstrass_model())
print("      (5 is the unramified quadratic class: Q_2(sqrt 5) = Q_4)")
print()
im_minus = [KK(1), 1 - om, om - 4, -3 - om]          # y^2 = x^3-1,  root om
im_plus  = [KK(1), -2 - om, -5 - om, -3 - om]        # y^2 = x^3+1,  root zeta_6 = 1+om

print("Im(delta), this notebook (b=3, root e*om) :", sorted(coords(z) for z in im))
print("Im(delta), b = -1        (root om)        :", sorted(coords(z) for z in im_minus))
print("   canonically equal ?                    ",
      sorted(coords(z) for z in im) == sorted(coords(z) for z in im_minus))
print()
print("b = 1: the normalised root is (-1)^(1/3)*om = -om, not the zeta_6 = -om^2 used there,")
print("       so its image must be conjugated before comparing:")
print("Im(delta), b = 1, root zeta_6             :", sorted(coords(z) for z in im_plus))
print("Im(delta), b = 1, root -om  (= sigma of it):", sorted(coords(sig(z)) for z in im_plus))
print("   equal to this notebook's image ?       ",
      sorted(coords(sig(z)) for z in im_plus) == sorted(coords(z) for z in im))
print("   (the image is not sigma-stable:", sorted(coords(sig(z)) for z in im) != sorted(coords(z) for z in im), ")")

3/(-125) = -3/125    class in Q_2^*/squares: (0, 1)    a square in Q_2 ? True
   => y^2 = x^3+3  ~  y^2 = x^3-125 over Q_2, and
      y^2 = x^3-125 = Elliptic Curve defined by y^2 = x^3 - 125 over Rational Field
      (5 is the unramified quadratic class: Q_2(sqrt 5) = Q_4)

Im(delta), this notebook (b=3, root e*om) : [(0, 0, 0, 0), (0, 0, 0, 1), (0, 0, 1, 0), (0, 0, 1, 1)]
Im(delta), b = -1        (root om)        : [(0, 0, 0, 0), (0, 0, 0, 1), (0, 0, 1, 0), (0, 0, 1, 1)]
   canonically equal ?                     True

b = 1: the normalised root is (-1)^(1/3)*om = -om, not the zeta_6 = -om^2 used there,
       so its image must be conjugated before comparing:
Im(delta), b = 1, root zeta_6             : [(0, 0, 0, 0), (0, 0, 0, 1), (0, 0, 1, 0), (0, 0, 1, 1)]
Im(delta), b = 1, root -om  (= sigma of it): [(0, 0, 0, 0), (0, 0, 1, 1), (0, 1, 0, 1), (0, 1, 1, 0)]
   equal to this notebook's image ?        False
   (the image is not sigma-stable: True )


So of the three curves, $b = -1$ and $b = 3$ share their local Kummer image on the nose — they are
unramified twists of one another over $\mathbb{Q}_2$ — while $b = 1$ sits at the Frobenius conjugate,
the other Lagrangian through $[\,\cdot\,]$; this is the same phenomenon recorded in §8 of the
$x^3-1$ notebook, seen from the other side.

## Summary

$$V = \Big\{\mathcal{O},\ \big(\sqrt[3]{-3},0\big),\ (1,2),\ \big(\tfrac14,\tfrac18\sqrt{193}\big)\Big\},
\qquad \operatorname{Im}(\delta) = \big\langle [1-\omega],\ [-3-\omega]\big\rangle .$$

- $E[2](\mathbb{Q}) = 0$ but $E[2](\mathbb{Q}_2) \neq 0$: every $2$-adic unit is a cube, so
  $e = \sqrt[3]{-3} \in \mathbb{Z}_2$ and $T = (e,0)$ is a local $2$-torsion point with irrational
  $x$-coordinate — $V$ contains a point that no rational search would ever produce;
- $e \equiv 5 \pmod{128}$ and square classes see only three binary digits, so
  $\delta(x,y) = x-e\omega$ may be replaced by $x-5\omega$ exactly, keeping all bookkeeping in
  $\mathbb{Q}(\omega)$;
- the norm map carries the image isomorphically onto $\mathbb{Z}_2^\times/(\mathbb{Z}_2^\times)^2$,
  and the four norm classes $1,5,3,7 \bmod 8$ match the four layers
  $E_2,\ E_1\smallsetminus E_2,\ T+E_2,\ T+(E_1\smallsetminus E_2)$;
- the coset of $Q$ contains no point with integral $x$, so $V$ reaches into the formal group;
  $E(\mathbb{Q}_2) = E_1 \oplus \langle T\rangle$ is pro-$2$, of type $\mathrm{II}$ with $c_2 = 1$;
- the image consists of **unit** classes although the reduction at $2$ is additive, and it is maximal
  isotropic for the Frobenius-twisted Hilbert symbol, as local duality demands;
- over $\mathbb{Q}_2$ this curve is the unramified quadratic twist of $y^2 = x^3-1$, and the two
  images coincide under the canonical, $\mathbb{Q}_2$-rational identification of their $2$-torsion.